// Übungs-Bibliothek fuer den Plan-Composer.
//
// Pro Problem-Typ (pulling, barking, etc.) gibt es eine Liste von
// Übungen mit Schwierigkeit, Phase und Tags. Der Composer waehlt aus
// dieser Liste die passenden Übungen basierend auf Hund-Profil aus
// und verteilt sie ueber die Wochen.
//
// Plus Phasen-Strukturen (Wochenziele, Tagespläne, No-Gos, Fortschritt)
// als Template pro Phase.

export type ProblemKey =
  | "pulling"
  | "barking"
  | "aggression"
  | "anxiety"
  | "recall"
  | "energy"
  | "jumping"
  | "destructive"
  | "soiling"
  | "mouthing";

export type Phase = "fundament" | "steigerung" | "generalisierung";
// fundament:        Wochen 1-4  (drinnen, reizarm)
// steigerung:       Wochen 5-8  (raus, kontrolliert)
// generalisierung:  Wochen 9-12 (Alltag, schwierige Situationen)

export type Difficulty = "easy" | "medium" | "hard";

export interface ExerciseTemplate {
  id: string;
  title: string;        // "SCHAU-Signal etablieren"
  shortDesc: string;    // 1-Satz für Wochen-Overview-Listen
  intro: string;        // 1-2 Sätze, kann {dogName} enthalten
  steps: string[];      // 6-8 Schritte, je Schritt mit "Titel: Beschreibung" Pattern oder freier Text
  phase: Phase;
  difficulty: Difficulty;
  durationMin: number;  // Geschätzte Dauer pro Session
  suitableFor: {
    minAgeMonths?: number;       // z.B. 6 für "nicht für junge Welpen"
    notForBreeds?: string[];     // z.B. ["mastiff"] für Übungen die zu anspruchsvoll
    notForSeniors?: boolean;     // true wenn nicht für Senior-Hunde
  };
  tags?: string[];      // freie Tags für später
}

export interface WeekStructure {
  num: number;
  title: string;
  wochenziele: string[];
  tagesplan: string;
  no_gos: string[];
  fortschritt: string[];
  // Welche Übungen kommen rein — werden vom Composer eingesetzt
  exerciseIds: string[];
}

// ════════════════════════════════════════════════════════════════════
// PULLING (Leinenziehen) — 12 Übungen + 12 Wochen-Templates
// ════════════════════════════════════════════════════════════════════

const PULLING_EXERCISES: ExerciseTemplate[] = [
  // ── Fundament (Woche 1-4) ──────────────────────────────────────
  {
    id: "p-schau",
    title: "SCHAU-Signal etablieren",
    shortDesc: "Aufmerksamkeit auf Signal — die Grundlage für alles weitere",
    intro: "Mit dieser Übung lernt {dogName} auf das Signal SCHAU sofort Blickkontakt mit dir aufzunehmen. Sie ist die Basis für alle weiteren Leinenführungs-Übungen.",
    steps: [
      "Halte ein Leckerli neben dein Gesicht auf Augenhöhe, sage SCHAU und warte, bis {dogName} dich ansieht.",
      "Sobald {dogName}s Blick deine Augen trifft, sage sofort FEIN in warmem Ton und gib das Leckerli.",
      "Wiederhole 5 mal hintereinander, dann eine Pause von 30 Sekunden.",
      "Bewege das Leckerli schrittweise vom Gesicht weg, damit {dogName} dich anschaut statt die Hand.",
      "Steigere die Dauer des Blickkontakts langsam auf 2-3 Sekunden bevor du FEIN sagst.",
      "Übe in verschiedenen Räumen, damit {dogName} das Signal nicht nur mit einem Ort verknüpft.",
      "Belohne besonders ruhigen, weichen Blickkontakt mit einem Jackpot aus 3-4 Leckerlis.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "p-leinenspiel-drinnen",
    title: "Leinen-Spiel in der Wohnung",
    shortDesc: "Lockere Leine drinnen üben bevor es nach draußen geht",
    intro: "{dogName} lernt das Grundprinzip der lockeren Leinenführung in reizarmer Umgebung. Drinnen, ohne Ablenkung — perfekt für den Anfang.",
    steps: [
      "Lege {dogName} die Leine an und starte in einem ruhigen Raum.",
      "Gehe entspannt los, die Leine locker in der Hand.",
      "Sobald die Leine straff wird, bleibe sofort und kommentarlos stehen wie eine Statue.",
      "Sobald {dogName} sich zu dir umdreht oder die Leine lockert, sage FEIN und gehe weiter.",
      "Übe Richtungswechsel: sage HIER, drehe dich und gehe in die andere Richtung.",
      "Belohne {dogName} großzügig wenn sie den Richtungswechsel mitmacht.",
      "Halte die Übung bei 5-7 Minuten und beende solange sie noch aufmerksam mitarbeitet.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 7,
    suitableFor: {},
  },
  {
    id: "p-stop-and-go",
    title: "Stop-and-Go an der Tür",
    shortDesc: "Vor dem Losgehen Ruhe etablieren — Hektik vermeiden",
    intro: "Ein ruhiger Start an der Haustür bestimmt den Rest des Spaziergangs. {dogName} lernt: Tür geht nur bei Ruhe auf.",
    steps: [
      "Leine anlegen, ruhig stehen bleiben — kein Losgehen.",
      "Türgriff anfassen, ohne zu öffnen. Bei Drängeln: Griff loslassen, warten.",
      "Tür einen Spalt öffnen. Bei Drängen: schließen, warten.",
      "Erster Schritt nach draußen: du zuerst, {dogName} folgt ohne vorbeizudrängen.",
      "Draußen 2-5 Sekunden stehen bleiben, ankommen lassen.",
      "Losgehen erst bei lockerer Leine. Ziehen bedeutet Stopp.",
      "Bei jedem Spaziergang anwenden — wird zur Routine.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 4,
    suitableFor: {},
  },
  {
    id: "p-baum",
    title: "Sei ein Baum: Stopp bei straffer Leine",
    shortDesc: "Die Kerntechnik gegen Ziehen: Leine straff = du stehst still wie ein Baum",
    intro: "Das ist die wichtigste Übung des ganzen Plans. {dogName} lernt: zieht die Leine, geht es nicht weiter. Lässt {dogName} nach, geht es weiter. Keine Strafe, keine Aufregung, einfach Konsequenz.",
    steps: [
      "Leine anlegen, beginne in einem ruhigen Flur oder Zimmer mit mindestens 4 Schritten Strecke.",
      "Geh entspannt los. Die Leine hängt locker, du hältst sie ohne Spannung.",
      "Sobald die Leine straff wird: SOFORT stehen bleiben. Keine Worte, kein Ruck, kein Blick zu {dogName}.",
      "Stehe wie ein Baum. Schau geradeaus oder neutral weg. Halte die Leine an dem Punkt fest, an dem sie war.",
      "Warte. {dogName} wird irgendwann nachgeben oder sich umdrehen.",
      "Sobald die Leine wieder locker ist (auch nur einen Moment): ruhig FEIN sagen und ohne Aufregung weitergehen.",
      "Pro Session 5-7 Minuten. Erwarte 15-25 Stopps am Anfang, das ist normal.",
      "Niemals an der Leine rucken oder schimpfen. Du bist nur ruhige Konsequenz, keine Strafe.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 6,
    suitableFor: {},
  },
  {
    id: "p-bei-fuss-belohnen",
    title: "Bei-Fuß-Position als Goldzone aufbauen",
    shortDesc: "Den Platz an deiner Seite zum lohnenswertesten Ort beim Spazierengehen machen",
    intro: "{dogName} soll lernen: die Position direkt neben deinem Bein ist der beste Platz beim Gehen. Wir verknüpfen die Bein-Position systematisch mit Belohnung, ohne sie zu erzwingen.",
    steps: [
      "Steh entspannt. Halte die Leckerlis in der Hand, die nahe an {dogName}s Laufseite ist (Hund links → linke Hand).",
      "Warte, bis {dogName}s Schulter neben deinem Knie ist. Sage HIER und gib das Leckerli direkt an der Naht der Hose, auf Bein-Höhe.",
      "Wiederhole 10x aus dem Stand. {dogName} lernt: Platz an deinem Knie = Leckerli kommt von oben.",
      "Mache jetzt einen einzigen Schritt nach vorne. Wenn {dogName} mitkommt und neben dem Bein bleibt: sofort Leckerli an der Naht.",
      "Steigere langsam: 2 Schritte, 3, 5. Belohne jeweils an der Bein-Position.",
      "Bei 10 Schritten ohne Ziehen: kleiner Jackpot von 3 Leckerlis hintereinander, dann beenden.",
      "Übe an 4-5 Tagen die Woche je 5 Minuten. Das ist Investition in deinen ganzen Plan.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 7,
    suitableFor: {},
  },
  {
    id: "p-baum-draussen",
    title: "Sei ein Baum draußen: Erster echter Test",
    shortDesc: "Die Stopp-Technik raus auf die ruhige Straße oder in den Hof übertragen",
    intro: "{dogName} hat drinnen gelernt: straffe Leine = stopp. Jetzt nimmst du das mit nach draußen. Die ersten Spaziergänge dieser Phase dauern länger und sind anstrengender, das ist Investition.",
    steps: [
      "Wähle eine ruhige Straße oder den Hof. KEINE Hauptstraße, KEINE Hundeauslaufzone.",
      "Plane doppelte Zeit ein. Wenn du sonst 20 Min brauchst, plane 40.",
      "Geh los wie gewohnt. Bei der ersten straffen Leine: SOFORT stehen bleiben wie drinnen geübt.",
      "Keine Worte, kein Ruck, kein Schauen. Statue-Modus.",
      "{dogName} wird verwundert sein. Es kann 30 Sekunden dauern bis sie sich umdreht. Halte aus.",
      "Sobald Leine locker: FEIN und weiter.",
      "Erwarte 30-50 Stopps in der ersten Session. Jeder Stopp ist ein Lernmoment.",
      "Mache zwischendrin alle 30 Schritte ein Bei-Fuß-Leckerli wenn locker. Belohne aktiv.",
      "Beende immer mit einer lockeren Phase, auch wenn nur 2 Minuten — niemals nach einem Pulling-Moment.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 25,
    suitableFor: {},
  },
  {
    id: "p-penalty-yards",
    title: "Penalty Yards: Gegenrichtung als Konsequenz",
    shortDesc: "Wenn Stoppen nicht reicht, wird Pullen zur Sackgasse durch Umkehren",
    intro: "Verstärkung von Sei-ein-Baum: bei hartnäckigem Ziehen drehst du um und gehst ein paar Schritte zurück. {dogName} lernt: Pullen führt nicht zum Ziel, sondern davon weg.",
    steps: [
      "Wende diese Übung NUR an, wenn das reine Stehenbleiben nach 30 Sekunden nichts bewirkt.",
      "Bei hartnäckigem Ziehen: dreh dich ruhig um (nicht ruckartig).",
      "Gehe 4-5 entspannte Schritte in die Gegenrichtung. Ohne Wort, ohne Drama.",
      "{dogName} folgt: gehe weiter in der ursprünglichen Richtung. Locker werden = weiter geht's.",
      "Pro Spaziergang max 5-6 Penalty-Yards-Episoden, sonst wird's für beide frustrierend.",
      "Wichtig: ruhig bleiben. Du teachst, nicht bestrafst. Bewegung ist die Botschaft.",
      "Direkt nach der Umkehr beim Wieder-richtig-laufen: großzügig belohnen an der Bein-Position.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "p-tempo-wechsel",
    title: "Tempo-Wechsel als Aufmerksamkeits-Tool",
    shortDesc: "Plötzliche Tempo-Änderung macht {dogName} aufmerksam und das Gehen interessanter",
    intro: "Mit unvorhersehbaren Tempo-Wechseln zwingst du {dogName}, sich an dir zu orientieren. Spaziergänge werden spielerischer und {dogName} bleibt mental dabei.",
    steps: [
      "Beginne mit normalem Tempo bei lockerer Leine.",
      "Plötzlich (ohne Ankündigung) auf halbes Tempo reduzieren.",
      "{dogName} passt das Tempo an? Sofort FEIN und Leckerli an der Bein-Position.",
      "Nach 8-10 Schritten: plötzlich auf doppeltes Tempo beschleunigen, fast Joggen.",
      "Wieder Anpassung? Wieder Belohnung an der Bein-Position.",
      "Pro Spaziergang 6-10 solche Tempo-Wechsel.",
      "Variation: kurze 90-Grad-Drehung statt Tempo-Wechsel, gleicher Effekt.",
      "Kein starres Schema, sei unberechenbar — das ist gerade der Reiz.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "p-lockere-leine-aussen",
    title: "Lockere Leine im echten Alltagsspaziergang",
    shortDesc: "Alle Techniken kombiniert: Stopp, Bei-Fuß, Tempo, Schnüffeln als Belohnung",
    intro: "Das ist der Alltagstest. {dogName} kennt jetzt Sei-ein-Baum, Bei-Fuß-Belohnung und Tempo-Wechsel. Jetzt kombinierst du alle Werkzeuge auf einer normalen Strecke.",
    steps: [
      "Plane einen 20-30-Minuten-Spaziergang auf einer dir bekannten Strecke.",
      "Starte mit 2-3 Minuten Bei-Fuß-Belohnen, um {dogName} in den Trainings-Modus zu bringen.",
      "Bei jeder straffen Leine: Sei-ein-Baum-Stopp.",
      "Bei hartnäckigem Pullen: Penalty Yards.",
      "Alle 30-40 Schritte: Leckerli an der Bein-Position wenn locker.",
      "2-3 Mal pro Spaziergang: bewusster Tempo-Wechsel.",
      "Schnüffel-Pausen sind die beste Belohnung: lockere Leine = du darfst hin und schnüffeln.",
      "Beobachte: wo sind eure Hot-Spots? Notiere mental.",
      "Beende IMMER in einer lockeren Phase, auch wenn dafür der Spaziergang früher endet.",
    ],
    phase: "generalisierung",
    difficulty: "medium",
    durationMin: 25,
    suitableFor: {},
  },
  {
    id: "p-decke-drinnen",
    title: "Entspannungsdecke etablieren",
    shortDesc: "Einen Ruhe-Anker für später draußen aufbauen",
    intro: "{dogName} bekommt einen festen Ort drinnen — die Entspannungsdecke. Später nutzen wir den als Anker auch draußen.",
    steps: [
      "Lege eine Decke an einen ruhigen Ort, führe {dogName} hin und belohne das Betreten.",
      "Sobald {dogName} mit allen Pfoten auf der Decke ist, sage PLATZ.",
      "Gib alle 5 Sekunden ruhig ein Leckerli zwischen die Vorderpfoten.",
      "Verlängere die Abstände langsam auf 10 und dann 15 Sekunden.",
      "Sage FEIN in tiefer ruhiger Stimme — Entspannung verknüpfen, nicht Aufregung.",
      "Wenn {dogName} aufsteht: ruhig zurückführen, ohne Worte.",
      "Beende mit klarem Auflöse-Signal wie LAUF.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },

  // ── Steigerung (Woche 5-8) ─────────────────────────────────────
  {
    id: "p-schau-draussen",
    title: "SCHAU mit Außenablenkung",
    shortDesc: "Das Signal funktioniert auch wenn draußen was los ist",
    intro: "{dogName} überträgt das gelernte SCHAU-Signal in die Außenwelt — anfangs an ruhigen Orten, dann mit mehr Ablenkung.",
    steps: [
      "Beginne jeden Spaziergang mit einer kurzen SCHAU-Übung vor der Haustür.",
      "Übe 5-7 Minuten lockere Leinenführung an einem ruhigen Ort ohne Passanten.",
      "Bei jedem auffälligen Reiz (Auto, anderer Hund in Distanz): SCHAU und Leckerli.",
      "Wenn {dogName} reagiert ohne SCHAU zu hören — Jackpot von 4-5 Leckerlis.",
      "Steigere die Ablenkung langsam: erst leichte Reize, dann mehr.",
      "Bei Stress-Signalen: Abstand vergrößern, einfacher machen.",
      "Beende immer in einer entspannten Situation — Erfolg festigen.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "p-bogen",
    title: "BOGEN bei Begegnungen",
    shortDesc: "Strukturiertes Ausweichen statt Ziehen oder Bellen",
    intro: "Mit dieser Übung lernt {dogName} eine klare Ausweichstrategie — den Bogen — die das Ziehen bei Begegnungen ersetzt.",
    steps: [
      "Übe den Bewegungsablauf ohne echte Begegnung: gehe mit {dogName} um Laternen oder Mülleimer herum.",
      "Sage dabei BOGEN und locke {dogName} mit einem Leckerli in den Halbkreis.",
      "Belohne {dogName} alle 2-3 Schritte während des Bogens.",
      "Fordere während des Bogens SCHAU, um die Aufmerksamkeit zu halten.",
      "Steigere auf echte Begegnungen mit großem Abstand (15+ Meter).",
      "Nach jeder erfolgreichen Begegnung: Jackpot aus 3-4 Leckerlis.",
      "Verringere den Bogenradius erst wenn {dogName} entspannt bleibt.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "p-gegenkonditionierung",
    title: "Gegenkonditionierung auf Reize",
    shortDesc: "Reize positiv verknüpfen — vom Stressor zur Belohnung",
    intro: "{dogName} lernt: Reize bedeuten nicht Aufregung, sondern Leckerlis. Wir verändern die emotionale Reaktion grundlegend.",
    steps: [
      "Setze dich mit {dogName} an einen Ort mit Reizen in 15-20m Distanz.",
      "Sobald ein Reiz auftaucht (Mensch, Hund, Auto): sage SCHAU und füttere durchgehend.",
      "Füttere solange der Reiz sichtbar ist, NICHT erst nach Reaktion.",
      "Sobald der Reiz weg ist: Leckerlis stoppen vollständig.",
      "{dogName} lernt: Reiz erscheint = Leckerli, Reiz weg = Leckerli vorbei.",
      "Beobachte Körpersprache: bei Anspannung mehr Abstand schaffen.",
      "Max 5 Begegnungen pro Einheit — Qualität vor Quantität.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "p-richtungswechsel-aussen",
    title: "Richtungswechsel ohne Ansage",
    shortDesc: "Aufmerksamkeit bei dir statt nach vorne ziehen",
    intro: "{dogName} entwickelt Aufmerksamkeit für deine Bewegung. Statt vor zu rennen, orientiert sie sich an dir.",
    steps: [
      "Gehe normal weiter, Leine locker.",
      "Plötzlich Richtung wechseln — ohne etwas zu sagen.",
      "Bei Folgen mit kurzer Verzögerung: ruhig bestätigen.",
      "Bei Zug zurück zur richtung: stehen bleiben.",
      "Sobald Leine locker, weitergehen.",
      "2-3 Richtungswechsel pro Spaziergang.",
      "Kein Rucken oder Ankündigen — nur Bewegung als Signal.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 5,
    suitableFor: {},
  },

  // ── Generalisierung (Woche 9-12) ──────────────────────────────
  {
    id: "p-vorbeigang",
    title: "Direktes Vorbeigehen an Menschen",
    shortDesc: "An Menschen vorbei ohne Bogen — die Königsdisziplin",
    intro: "Jetzt geht's an die schwerere Variante: {dogName} lernt direkt an Menschen in 3-5m Distanz vorbeizugehen ohne Bogen.",
    steps: [
      "Wähle zunächst Wege mit niedrigem Menschen-Aufkommen.",
      "Bereite {dogName} schon aus 15m Distanz mit SCHAU vor.",
      "Halte das Tempo konstant — nicht schneller, nicht langsamer.",
      "Belohne während des Vorbeigangs kontinuierlich mit kleinen Leckerlis (Pippeling-Modus).",
      "Wenn {dogName} stress-frei vorbeigeht: 5 Sekunden nach Passage Jackpot.",
      "Vermeide direkten Blickkontakt mit dem entgegenkommenden Menschen.",
      "Bei Anspannung: zurück zum BOGEN, ohne Frust.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 15,
    suitableFor: {},
  },
  {
    id: "p-cafe",
    title: "Café-Außenbereich-Training",
    shortDesc: "Ruhig liegen während du Kaffee trinkst",
    intro: "{dogName} lernt, in einer Café-Situation ruhig zu warten. Das ist Premium-Alltag — ein echtes Highlight im Plan.",
    steps: [
      "Wähle ein Café mit ruhigem Außenbereich, nicht zentral.",
      "Lege die Decke vor oder unter den Tisch.",
      "Bestelle erst wenn {dogName} sich abgelegt hat.",
      "Belohne in der ersten Minute mehrfach für ruhiges Liegen.",
      "Reduziere die Belohnungs-Frequenz langsam.",
      "Bei Aufstehen: ruhig zurückführen, ohne Worte.",
      "Beende nach 15 Minuten — auch wenn's super lief.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 15,
    suitableFor: {},
  },
  {
    id: "p-stadt-spaziergang",
    title: "Stadtspaziergang in moderater Fußgängerzone",
    shortDesc: "Die Endprüfung — Stadtbummel mit lockerer Leine",
    intro: "Jetzt zeigt sich was {dogName} gelernt hat: ein Spaziergang durch eine moderate Fußgängerzone, voll mit Reizen.",
    steps: [
      "Wähle eine ruhigere Fußgängerzone, nicht den Hauptboulevard.",
      "Beginne früh mit SCHAU vor der Tür.",
      "Alle bekannten Strategien einsetzen: SCHAU, BOGEN, Richtungswechsel.",
      "Bei Stress: rausgehen, kein Ego-Trip.",
      "Nutze Schnüffel-Pausen aktiv als Cool-Down.",
      "Halte den Spaziergang kurz, max 30 Min.",
      "Beende immer in einer ruhigen Situation.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 20,
    suitableFor: { minAgeMonths: 12 },
  },
  {
    id: "p-wartungs-spaziergang",
    title: "Wartungs-Spaziergang im Alltag",
    shortDesc: "Was wir gelernt haben in den Alltag tragen",
    intro: "{dogName}s neue Verhaltensmuster werden zur Alltagsroutine. Du musst nicht mehr trainieren — du lebst es.",
    steps: [
      "Reduziere bewusst die Belohnungs-Frequenz: alle 30 Schritte statt alle 10.",
      "Belohne weiterhin Spitzenleistungen mit Jackpot.",
      "Beobachte ob {dogName} ohne Belohnung die Strategien zeigt.",
      "Wenn ja: weiter reduzieren, in kleinen Schritten.",
      "Wenn nein: kurz zurück zur höheren Frequenz.",
      "Über die Zeit entwickelt sich ein Alltagsmodus.",
      "Nicht mehr Training, sondern gemeinsames Leben.",
    ],
    phase: "generalisierung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// ENERGY (zu viel Energie / Hyperarousal) — 10 Übungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: ein muede ausgelasteter Hund wird ruhig, nicht ein
// erschoepfter. Mehr Kopfarbeit + Nasenarbeit + Ruhe-Konditionierung
// schlaegt mehr Bewegung. Viele Halter machen den Fehler "mehr Action"
// und verstaerken damit Hyperarousal.

const ENERGY_EXERCISES: ExerciseTemplate[] = [
  {
    id: "e-such-drinnen",
    title: "Futter-Suche in der Wohnung",
    shortDesc: "Stumpfes Fressen wird zur 20-30-Minuten Nasenarbeit",
    intro: "Statt {dogName} die Schüssel hinzustellen, verteilst du das Trockenfutter in der Wohnung. {dogName} sucht systematisch, nutzt Nase und Kopf. Macht zufrieden und ruhig.",
    steps: [
      "Lass {dogName} in einem anderen Raum oder lass sie sitzen mit Sicht-Schutz.",
      "Verteile die normale Tagesmenge Trockenfutter portionsweise in einem Raum.",
      "Beginne einfach: sichtbare Stellen, neben dem Korb, auf dem Boden zwischen Beinen vom Sofa.",
      "Sage ruhig SUCH und gib die Erlaubnis loszuziehen.",
      "Lass {dogName} selbstständig suchen. NICHT helfen oder hinweisen.",
      "Steigere ab Tag 4: höhere Verstecke, hinter Gegenständen, an leicht ungewohnten Stellen.",
      "Pro Tag mind. 1 Mahlzeit als Suchspiel — 20-30 Min Beschäftigung statt 30 Sek aus der Schüssel.",
      "Nach dem Suchspiel: {dogName} darf von selbst zur Ruhe kommen. Nicht zum Spielen animieren.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 25,
    suitableFor: {},
  },
  {
    id: "e-kong-mahlzeit",
    title: "Kong oder Schnüffelmatte als Mahlzeit-Ersatz",
    shortDesc: "Mahlzeit aus Kong/Mat — Beschäftigung statt Schlingen",
    intro: "Eine Mahlzeit pro Tag kommt aus dem Kong oder einer Schnüffelmatte. {dogName} arbeitet 15-30 Min an seinem Futter statt es in 30 Sekunden zu schlingen. Mentale Auslastung pur.",
    steps: [
      "Stopfe einen Kong mit Nassfutter oder eingeweichtem Trockenfutter.",
      "Variante leichter: locker mit Leckerlis fuellen. Variante schwer: einfrieren, dann kniffliger.",
      "Bei Schnüffelmatte: Trockenfutter zwischen die Stoff-Streifen drücken.",
      "Übergebe {dogName} die Beschäftigung an einem ruhigen Ort: Decke, Korb, Hundezimmer.",
      "Du gehst weg. {dogName} arbeitet selbstständig.",
      "Beobachte nicht. Sei nicht im selben Raum aktiv. Sonst lenkt das ab.",
      "Pro Tag mind. 1 Mahlzeit so. Bei mehr Energie-Überschuss auch 2.",
      "Schnüffelmatten regelmäßig waschen, Kong nach jedem Mal ausspülen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 25,
    suitableFor: {},
  },
  {
    id: "e-warte-impuls",
    title: "WARTE als Impulskontroll-Signal",
    shortDesc: "Frust aushalten lernen vor Tür, Futter, Spielzeug",
    intro: "{dogName} lernt: Warten ist Teil des Lebens. Vor der Tür, dem Futternapf, dem Spielzeug. Impulskontrolle baut sich genau dadurch auf, und ein impulskontrollierter Hund ist ein ruhigerer Hund.",
    steps: [
      "Beginne mit dem Futternapf: stelle ihn hin, dann sage WARTE und Hand vor den Napf.",
      "{dogName} ist ungeduldig. Erwarte das.",
      "Sobald {dogName} 1 Sekunde ruhig ist (sitzen, stehen, nicht hinstürmen): FEIN + Erlaubnis HIER ist deins (Futter freigeben).",
      "Steigere täglich: 1 Sek → 3 Sek → 5 Sek → 10 Sek.",
      "Sobald 10 Sek sitzen, übertrage auf andere Situationen: WARTE vor der Tür, WARTE vor dem Spielzeug, WARTE vor dem Auto.",
      "Wichtig: niemals WARTE und dann das Objekt komplett verbieten. Es muss IMMER mit der Auflösung enden, sonst wird WARTE Strafe.",
      "Pro Tag 3-4 Mini-WARTE-Situationen einbauen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "e-entspannungs-marker",
    title: "Entspannungs-Anker konditionieren",
    shortDesc: "Ein Wort wird zum Off-Schalter für Aufregung",
    intro: "Du verknüpfst ein Wort wie WUNDERBAR oder LEISE mit ruhigen Zuständen, in denen {dogName} schon entspannt ist. Später kannst du das Wort einsetzen, um Ruhe zu fördern, wenn sie nicht von selbst kommt.",
    steps: [
      "Beobachte {dogName} 2-3 Tage. Notiere: wann ist {dogName} entspannt? Liegt im Korb, Augen halb zu, Atem ruhig.",
      "Gehe in diesen Momenten ruhig hin, sage in tiefer warmer Stimme WUNDERBAR.",
      "Streichle sanft und gib ein weiches Leckerli direkt ans Maul, ohne {dogName} hochzuholen.",
      "Wiederhole täglich 5-7 mal in solchen Ruhe-Momenten.",
      "Nach 7-10 Tagen testest du den Marker in moderater Aufregung: sage WUNDERBAR und beobachte, ob {dogName} langsamer wird.",
      "Wenn ja: in Aufregungs-Momenten als Werkzeug einsetzen. Nicht inflationär, sondern gezielt.",
      "Wenn nein: weitere Woche nur in Ruhe-Momenten verknüpfen. Der Marker muss eindeutig konditioniert sein.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 3,
    suitableFor: {},
  },
  {
    id: "e-shape-trick",
    title: "Shape-Training: ein einfacher Trick",
    shortDesc: "{dogName} probiert selbst aus, was zum Klick führt — Kopfauslastung pur",
    intro: "Bei Shape lernt {dogName} eigenständig, indem du jeden Schritt in die richtige Richtung markierst. Klassischer Trick zum Einstieg: ein Pfötchen heben oder auf eine Decke gehen. Kopfarbeit der besten Sorte.",
    steps: [
      "Wähle einen einfachen Trick: PFOTE auf deine Hand legen.",
      "Setze dich auf den Boden vor {dogName}. Hand entspannt halten.",
      "Warte. Sobald {dogName} eine Pfote auch nur leicht hebt: sofort FEIN und Leckerli.",
      "Wiederhole. {dogName} wird neugierig: was hat ich gemacht?",
      "Erhöhe die Anforderung schrittweise: höher heben, auf Hand legen, länger halten.",
      "Pro Session 5-7 Minuten. {dogName} muss aktiv denken, das wirkt schnell ermüdend.",
      "Wenn der Trick sitzt, neuen wählen: NASE auf Hand, DREH-DICH, TÜR-ZU.",
      "Im Trick-Modus: sehr ruhige Sessions, weiches Loben, niemals frustriert werden.",
    ],
    phase: "fundament",
    difficulty: "medium",
    durationMin: 7,
    suitableFor: {},
  },
  {
    id: "e-mantrailing-basis",
    title: "Mantrailing-Basis: Spur folgen draußen",
    shortDesc: "Nasenarbeit im Außenbereich — anspruchsvoll und befriedigend",
    intro: "{dogName} folgt einer Futter- oder Belohnungsspur, die du vorher gelegt hast. Nasenarbeit draußen ist eine der intensivsten kognitiven Beschäftigungen für Hunde. Nach 15 Min mantrailing ist auch ein Junghund ruhig.",
    steps: [
      "Beginne im eigenen Garten oder einem ruhigen Park.",
      "Lege eine 10m lange Spur aus Leckerlis im Abstand von 30-50 cm.",
      "Hole {dogName} und führe sie an den Spur-Anfang.",
      "Sage SUCH und lass {dogName} der Spur folgen, schnüffelnd.",
      "Bleibe ruhig dabei. Folge der Spur mit, ohne {dogName} zu drängen.",
      "Am Ende: Jackpot — ein Häufchen Leckerlis.",
      "Steigere täglich: längere Spur, ungleichere Abstände, andere Untergründe.",
      "Pro Spaziergang 1 Mantrailing-Einheit von 15-20 Min ersetzt 30 Min normales Laufen.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 20,
    suitableFor: {},
  },
  {
    id: "e-stop-spiel",
    title: "Stop-Spiel: Aufregung unterbrechen lernen",
    shortDesc: "{dogName} lernt mitten im Spiel auf STOP runterzukommen",
    intro: "Bei diesem Spiel lernt {dogName} eine wichtige Lebens-Skill: hochfahren und wieder runterkommen. Das ist Gold für Hunde mit zuviel Energie, weil sie das Off-Schalten oft nicht beherrschen.",
    steps: [
      "Beginne ein moderates Spiel mit Spielzeug oder Tausch-Geschäft.",
      "Nach 30-60 Sekunden Spiel: plötzlich STOP sagen und in Statue-Modus gehen.",
      "{dogName} ist erst irritiert. Halte aus. KEINE Wiederholung des STOP.",
      "Sobald {dogName} sich beruhigt (sitzt, steht ruhig, schaut dich an): FEIN.",
      "Belohne mit einem Leckerli, NICHT mit Wiederaufnahme des Spiels.",
      "5-10 Sekunden Pause halten, dann Spielzeug freigeben mit OK.",
      "Pro Session 4-6 STOP-Momente, dann beenden.",
      "{dogName} lernt: aufregung kann unterbrochen werden, ohne dass alles vorbei ist.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 7,
    suitableFor: {},
  },
  {
    id: "e-cool-down-decke",
    title: "Cool-Down auf der Decke",
    shortDesc: "Bewusstes Runterkommen nach Aufregung — Ruhe als trainierbare Fähigkeit",
    intro: "Nach jeder aufregenden Phase (Spiel, Besuch, Spaziergang) folgt eine 5-10 Min Cool-Down-Routine auf der Decke. {dogName} lernt: nach Aufregung kommt aktive Ruhe, nicht von alleine.",
    steps: [
      "Sobald {dogName} hochgefahren ist (von Spiel oder Besuch), führe sie ruhig zur Decke.",
      "Sage PLATZ in ruhiger Stimme.",
      "Setze dich daneben, streichle sanft am Schulterblatt.",
      "Atme bewusst tief und langsam — {dogName} synchronisiert.",
      "Wenn {dogName} hochsteht: ruhig zurückführen, ohne Worte.",
      "Alle 30-60 Sek einen weichen Leckerli zwischen die Vorderpfoten legen, wenn {dogName} liegt.",
      "5-10 Minuten halten, dann ruhiges Auflöse-Signal LAUF.",
      "Nach 2-3 Wochen wird die Cool-Down-Routine zur normalen Sequenz nach Aufregung.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "e-auslastungs-plan",
    title: "Auslastungs-Wochenplan",
    shortDesc: "Strukturierte Mischung aus Bewegung, Nasenarbeit, Kopfarbeit, Sozial",
    intro: "{dogName} braucht keine 4 Stunden Auslauf, sondern eine Mischung aus 4 Auslastungs-Arten pro Woche: körperlich, Nase, Kopf, sozial. Mit Plan ist das machbar, ohne Plan wird's Chaos.",
    steps: [
      "Erstelle einen 7-Tage-Plan in einem Notizbuch oder am Kühlschrank.",
      "Pro Tag: 1 körperliche Auslastung (Spaziergang 30-60 Min mit Tempo-Wechseln, nicht stumpf).",
      "Pro Tag: 1 Nasenarbeit-Einheit (Suchspiel, Schnüffelmatte, Mantrailing).",
      "Pro Tag: 1 Kopfarbeit (Shape-Trick, neue Übung, Kong, Puzzle).",
      "3-4x die Woche: sozialer Kontakt (Spaziergang mit Hundefreund, Besuch).",
      "Niemals mehr als 2-3 hoch-aufregende Aktivitäten am selben Tag.",
      "Schlaf einplanen: erwachsener Hund braucht 16-20h pro Tag.",
      "Plan an die Wand, jeden Abend Haken setzen. Du siehst Lücken sofort.",
    ],
    phase: "generalisierung",
    difficulty: "medium",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "e-anti-hyperarousal",
    title: "Anti-Hyperarousal-Routine",
    shortDesc: "Wenn {dogName} hochfährt: klare Sequenz zur Beruhigung",
    intro: "Manche Tage gehen schief. {dogName} ist hyperaktiv, kann nicht runterkommen. Statt zu reagieren mit mehr Action, gibt es jetzt eine klare 3-Schritt-Routine, die du immer einsetzen kannst.",
    steps: [
      "Schritt 1: alle Reize reduzieren. Ruhiger Raum, Licht dimmen, keine Geräusche.",
      "Schritt 2: {dogName} auf die Decke führen (oder hinsetzen, wenn sie schon dort ist).",
      "Schritt 3: Entspannungs-Marker WUNDERBAR setzen.",
      "Lange ruhige Sitzphase. Setze dich daneben, atme synchron tief.",
      "10-15 Minuten halten. {dogName} kommt fast immer runter, auch wenn anfangs zappelig.",
      "Wenn {dogName} ruhig wird: NICHT sofort wieder aktivieren. Mindestens 30 Min Ruhe-Phase.",
      "Mach NICHT den Fehler: nach Hyperaktivität noch eine Runde Tobereien, das verstärkt das Muster.",
    ],
    phase: "generalisierung",
    difficulty: "medium",
    durationMin: 15,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// AGGRESSION (Aggression in Begegnungen) — 7 Übungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: NIEMALS Konfrontation, IMMER Distanz. Schwellenwert-
// Arbeit + Gegenkonditionierung. Hund unter Schwellenwert lernt, daruber
// reagiert er nur. Maulkorb-Training ist Pflicht-Bestandteil fuer Sicher-
// heit und Flexibilitaet.

const AGGRESSION_EXERCISES: ExerciseTemplate[] = [
  {
    id: "a-maulkorb-positiv",
    title: "Maulkorb positiv konditionieren",
    shortDesc: "Bevor er gebraucht wird, muss der Maulkorb für {dogName} ein gutes Gefühl sein",
    intro: "Ein Maulkorb gehört ins Werkzeug-Set jedes Hundes mit Aggressions-Thema. Aber er funktioniert nur, wenn {dogName} ihn POSITIV verknüpft. Niemals beim ersten Mal aufsetzen und losgehen.",
    steps: [
      "Wähle einen gut sitzenden Korbmaulkorb (z.B. Baskerville Ultra), nicht Stoff.",
      "Tag 1-3: nur den Maulkorb sichtbar in der Wohnung liegen lassen. {dogName} ignoriert ihn.",
      "Tag 4: Leckerli durch die Gitterstäbe geben. {dogName} steckt die Nase rein, kassiert.",
      "Tag 5-7: {dogName} steckt aktiv die Schnauze in den Maulkorb, du gibst Leckerli, ziehst ihn sofort wieder raus.",
      "Tag 8-10: Maulkorb für 2-3 Sek geschlossen, sofort wieder ab. Belohnung durch die Gitterstäbe.",
      "Tag 11-14: Tragezeit auf 1, 2, 5 Min steigern. Mit Beschäftigung (Kong durch Gitter).",
      "Erster Spaziergang mit Maulkorb erst nach 14 Tagen positiver Verknüpfung.",
      "Niemals Maulkorb in Stress-Situation zum ersten Mal aufsetzen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "a-schwellenwert-finden",
    title: "Schwellenwert finden + dokumentieren",
    shortDesc: "Bevor du trainierst, musst du wissen ab welcher Distanz {dogName} reagiert",
    intro: "Die wichtigste Erkenntnis im Aggressions-Training: dein Hund kann unter Schwellenwert LERNEN, darüber nur reagieren. Du musst exakt wissen, wo dieser Wert liegt — pro Trigger-Typ unterschiedlich.",
    steps: [
      "Suche dir einen Ort wo {dogName}s typische Trigger berechenbar auftreten (Park-Eingang, Joggingstrecke).",
      "Stelle dich mit {dogName} an einer großen Distanz auf (50m+).",
      "Trigger erscheint: beobachte {dogName} GENAU.",
      "Suche nach diesen Zeichen: gespannte Mimik, fixe Augen, steifer Schwanz, Maul geschlossen, Atmung stockt.",
      "Sobald eines dieser Zeichen auftritt: du bist AM Schwellenwert. Distanz notieren.",
      "Reaktion (Bellen, Sprung, knurren): du bist DRÜBER. Distanz verdoppeln.",
      "Notiere pro Trigger-Typ (anderer Hund, Jogger, Fahrrad, Kind) die Schwellenwert-Distanz.",
      "Diese Werte sind dein Trainings-Boden: immer DARUNTER arbeiten, niemals daran kratzen.",
    ],
    phase: "fundament",
    difficulty: "medium",
    durationMin: 20,
    suitableFor: {},
  },
  {
    id: "a-lat",
    title: "Look at That (LAT): Reiz anschauen, dann zu dir",
    shortDesc: "{dogName} darf den Trigger ANSCHAUEN — dafür gibt es Belohnung",
    intro: "LAT ist das wichtigste Spiel im Aggressions-Training. Statt {dogName} vom Trigger wegzudrängen, darf er hinschauen, MUSS aber dann zu dir zurückschauen. Wir nutzen seine Neugier statt sie zu unterdrücken.",
    steps: [
      "Stelle dich mit {dogName} UNTER Schwellenwert auf (sicher).",
      "Trigger erscheint. {dogName} schaut hin.",
      "Sobald {dogName} hingeschaut hat: sage SCHAU und mache ein eindeutiges Geräusch (Klicker oder klares FEIN).",
      "{dogName} schaut zu dir: SOFORT Leckerli hochwertig.",
      "Wenn {dogName} nicht von selbst zu dir schaut: locke mit Leckerli aus der Hosentasche.",
      "Wiederhole bei jedem neuen Trigger-Sichtkontakt.",
      "{dogName} lernt: Trigger sehen = Belohnung beim Halter erwarten. Die emotionale Reaktion verändert sich grundlegend.",
      "WICHTIG: niemals OBERHALB des Schwellenwerts üben — dann wird es Konfrontation statt Lernen.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 15,
    suitableFor: {},
  },
  {
    id: "a-engage-disengage",
    title: "Engage-Disengage Protokoll",
    shortDesc: "Reiz wahrnehmen, dann aktiv abwenden",
    intro: "Aufbauend auf LAT: {dogName} lernt, sich nach dem Anschauen aktiv vom Trigger abzuwenden. Das ist die nächste Stufe — {dogName} wählt selbst die Strategie statt zu reagieren.",
    steps: [
      "Beginne unter Schwellenwert, mit funktionierendem LAT.",
      "Trigger erscheint. {dogName} schaut hin.",
      "Erst NACH der Anschau-Phase (1-2 Sek): warte ab.",
      "Wenn {dogName} von selbst wegschaut: SOFORT Jackpot von 3 Leckerlis. Großer Erfolg.",
      "Wenn {dogName} weiter starrt: leiser SCHAU-Hint geben.",
      "{dogName} lernt: nicht nur ich kann anschauen, ich kann auch SELBST abwenden.",
      "Über Wochen wird das Wegschauen automatisch.",
      "Tag-für-Tag-Steigerung: Distanz langsam reduzieren, immer in kleinen Schritten.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 15,
    suitableFor: {},
  },
  {
    id: "a-bogen-aktiv",
    title: "Aktiver Bogen mit Fluchtweg-Plan",
    shortDesc: "Strukturiertes Ausweichen mit klarer Strategie",
    intro: "Wenn ein Trigger zu eng kommt, brauchst du eine Handlungs-Strategie. Der aktive Bogen mit vorher geplanten Fluchtwegen ist deine Notfall-Antwort, ohne dass es zur Eskalation kommt.",
    steps: [
      "Bevor du Spaziergänge planst: notiere mental, wo deine Fluchtwege sind (Seitenstraßen, Hofeingänge, Bushaltestellen).",
      "Bei Trigger-Erscheinung: ruhig BOGEN sagen und dich um 90 Grad weg orientieren.",
      "Locke {dogName} mit Leckerli aus der Hosentasche in die neue Richtung.",
      "Gehe entschieden, aber NICHT panisch.",
      "Sobald du raus aus der Sicht-Linie bist: 3 Leckerlis ans Maul, Beruhigungs-Marker WUNDERBAR.",
      "{dogName} darf 1-2 Min an dem neuen Ort ankommen.",
      "Wichtig: niemals dem Trigger direkt ausweichen ohne {dogName}s Aufmerksamkeit zu lenken — Frust und Eskalation drohen.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "a-bat-distanz",
    title: "BAT: Behavior Adjustment Training in Distanz",
    shortDesc: "{dogName} lernt selbst zu entscheiden: bleiben oder weggehen",
    intro: "BAT ist die nächste Stufe nach LAT und Engage-Disengage. {dogName} bekommt die Kontrolle: er darf den Trigger beobachten und dann SELBST entscheiden, sich zu entfernen. Das stärkt sein Sicherheits-Gefühl massiv.",
    steps: [
      "Aufbau: 30m Distanz zum Trigger, Schleppleine 5m für mehr Bewegungsfreiheit.",
      "{dogName} schaut den Trigger an. Du beobachtest, machst NICHTS.",
      "Sobald {dogName} eine Stress-Lösungs-Bewegung macht (wegschauen, sich abwenden, schnüffeln, Boden lecken): SOFORT mit ihr aktiv mitgehen, weg vom Trigger.",
      "Das ist die Belohnung: Distanz vergrößern. Funktional, ohne Leckerli.",
      "Nach 10-20m: 1 Min Pause, schnüffeln lassen.",
      "Wiederhole 4-6 mal in einer Session.",
      "Über Wochen: {dogName} lernt eigene Schwellenwert-Regulation. Du musst weniger lenken.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 30,
    suitableFor: {},
  },
  {
    id: "a-emergency-protokoll",
    title: "Notfall-Protokoll bei Eskalation",
    shortDesc: "Wenn doch was passiert: klare Schritte, kein Chaos",
    intro: "Manchmal geht etwas schief, ein Hund kommt um die Ecke, du wirst überrascht. Du brauchst eine eingeübte Notfall-Sequenz, damit weder du noch {dogName} eskaliert.",
    steps: [
      "Schritt 1: KEIN Schreien, KEIN Ziehen. Schreien verstärkt {dogName}s Erregung.",
      "Schritt 2: kurz aber bestimmt ABBRUCH-Signal (vorher konditioniert mit Leckerli).",
      "Schritt 3: 90 Grad Wendung, gehe entschieden weg.",
      "Schritt 4: wenn {dogName} weiter eskaliert: kurz Abstand halten zwischen euch und Trigger (Mülltonne, Auto als Sichtschutz).",
      "Schritt 5: 50m weiter weg gehen, dann erst stoppen.",
      "Schritt 6: Beruhigungs-Marker WUNDERBAR und mehrere Leckerlis ans Maul.",
      "Schritt 7: nach 5 Min Pause: Spaziergang ruhig beenden, NICHT nochmal in Trigger-Bereich gehen.",
      "Nach Hause kommen: kein erneutes Aufregen. Cool-Down auf der Decke 15 Min.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 10,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// MOUTHING (Aufnehmen von Gegenständen) — 6 Übungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: AUS sauber aufbauen, Tausch statt Strafe, kurze Leine
// an Hotspots, Maulkorb fuer Uebergang. Niemals Hand in Maul greifen.

const MOUTHING_EXERCISES: ExerciseTemplate[] = [
  {
    id: "m-aus-aufbauen",
    title: "AUS sauber aufbauen drinnen",
    shortDesc: "Das wichtigste Signal: {dogName} gibt freiwillig her, ohne Druck",
    intro: "AUS muss positiv sein, sonst spuckt {dogName} nichts mehr aus. Wir bauen es so auf, dass {dogName} aktiv abgibt — weil sich das mehr lohnt als zu behalten.",
    steps: [
      "Beginne mit einem niedrigwertigen Gegenstand: ein einfaches Spielzeug, kein Lieblings-Knochen.",
      "{dogName} hat das Spielzeug. Du hältst ein wertvolles Leckerli auf Nase-Höhe.",
      "Sage ruhig AUS. KEIN drohender Ton.",
      "{dogName} lässt das Spielzeug fallen (irgendwann), um das Leckerli zu kassieren.",
      "Sofort FEIN + Leckerli + ZURÜCK das Spielzeug.",
      "{dogName} lernt: AUS = ich gebe etwas her und kriege etwas Besseres UND das Original zurück.",
      "Steigere Wertigkeit über 2 Wochen: einfaches Spielzeug → Lieblings-Spielzeug → Knochen (vorsichtig).",
      "Niemals reiß-AUS oder Hand-ins-Maul. Das vergiftet das Signal lebenslang.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "m-tausch-protokoll",
    title: "Tausch-Geschäft: höherwertig gegen Aufgehobenes",
    shortDesc: "Wenn {dogName} etwas im Maul hat, bekommt er etwas Besseres dafür",
    intro: "Mouthing-Hunde nehmen oft aus Neugier oder Selbstbelohnung auf. Statt Konflikt: angebotener Tausch. {dogName} lernt: hergeben ist besser als behalten, weil es immer aufwerten heißt.",
    steps: [
      "Wenn {dogName} etwas Falsches im Maul hat: NICHT sofort ranstürmen.",
      "Ruhig nah ran, Leckerli-Hand auf Nase-Höhe halten.",
      "Sage AUS in ruhiger Stimme.",
      "{dogName} spuckt aus für das Leckerli.",
      "Du nimmst das Aufgenommene auf, ohne dramatisch zu reagieren.",
      "Gib zur Belohnung noch ein zweites Leckerli, manchmal sogar ein Spielzeug.",
      "Wichtig: niemals dem Hund hinterherrennen, das ist Spiel für ihn.",
      "Wichtig: niemals das aufgehobene Ding zurückgeben, sonst ist der Tausch nicht echt.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "m-pfui-konditionieren",
    title: "PFUI konditionieren als Stop-Signal",
    shortDesc: "Ein klares STOPP-Signal, bevor {dogName} aufhebt",
    intro: "PFUI wird als Stopp-Signal eingesetzt, BEVOR {dogName} etwas aufnimmt. Konditioniert mit konsequenter Anwendung und alternativer Belohnung, wird PFUI über Wochen automatisch.",
    steps: [
      "Konditioniere drinnen mit einem Leckerli auf dem Boden, das {dogName} nicht haben darf.",
      "Sage in dem Moment wo {dogName} sich danach beugt: PFUI in fester aber ruhiger Stimme.",
      "Locke {dogName} mit einem hochwertigen Leckerli aus der Hand weg.",
      "Sobald {dogName} sich entfernt: FEIN + Leckerli.",
      "Wiederhole 5-7 mal pro Session, über 1-2 Wochen drinnen.",
      "Übertrage dann nach draußen: PFUI wenn {dogName} sich zum Aufheben beugt.",
      "Wichtig: PFUI niemals als reine Strafe. Es muss IMMER eine Alternativ-Belohnung folgen.",
      "Wenn PFUI nach 4 Wochen draußen nicht greift: zurück zur Wohnung, neu konditionieren.",
    ],
    phase: "fundament",
    difficulty: "medium",
    durationMin: 7,
    suitableFor: {},
  },
  {
    id: "m-leinen-management",
    title: "Leinen-Management an Hotspots",
    shortDesc: "Kurz halten wo viel zu finden ist — Prävention statt Reaktion",
    intro: "Aufnehmen ist selbst-belohnend. Verhindere es lieber, als ständig zu korrigieren. An Hotspots (Mülltonnen, Park-Eingang, Spielplätze) hältst du die Leine kurz und lenkst aktiv ab.",
    steps: [
      "Identifiziere euer typische Hotspot-Strecke: wo nimmt {dogName} am häufigsten auf?",
      "Vor diesen Stellen: Leine auf 1m verkürzen, {dogName} dicht an dein Bein.",
      "Mache aktiv Bein-Position-Belohnungen während der Hotspot-Passage.",
      "Zähle in Gedanken: 1-2-3-4-5, alle 5 Schritte ein Leckerli an der Bein-Naht.",
      "Sobald ihr durch seid: Leine wieder lockern, normale Bewegung erlauben.",
      "{dogName} lernt: an diesen Stellen läuft was anderes ab. Aufmerksamkeit beim Halter zahlt sich aus.",
      "Über Wochen reduziert sich das Aufnehmen an diesen Spots, weil die Aufmerksamkeit umverteilt ist.",
    ],
    phase: "steigerung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "m-maulkorb-uebergang",
    title: "Maulkorb für die Übergangszeit",
    shortDesc: "Sicherheit an Hochrisiko-Orten, bis das Training greift",
    intro: "Solange das Training noch nicht steht, ist ein Maulkorb das beste Sicherheits-Equipment. Nicht aus Strafe, sondern aus Vernunft — Giftköder und scharfe Gegenstände gibt es überall.",
    steps: [
      "Konditioniere den Maulkorb positiv (siehe Aggression-Maulkorb-Übung, gleiche Methode).",
      "Wenn die positive Verknüpfung steht: Maulkorb an Hochrisiko-Orten einsetzen.",
      "Niemals als Strafmaßnahme nutzen, niemals zu Hause aufsetzen wegen Frust.",
      "Mit Maulkorb kann {dogName} normal trinken und schnüffeln, nur nicht aufnehmen.",
      "Idealerweise Korbmaulkorb (Baskerville Ultra, BUMAS), keine Stoff-Maulschlinge.",
      "Trainings-Plan parallel weiterführen, Maulkorb wird mit der Zeit überflüssig.",
    ],
    phase: "steigerung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "m-belohnungs-suche",
    title: "Belohnungs-Suche als Alternativ-Beschäftigung",
    shortDesc: "Statt aufnehmen suchen lassen — nutzt den natürlichen Trieb produktiv",
    intro: "Hunde mit starkem Aufnehmer-Trieb haben oft hohe Suchmotivation. Statt die zu unterdrücken, kanalisierst du sie in Belohnungs-Suchspiele draußen. Beschäftigt den Trieb produktiv.",
    steps: [
      "An sicheren Stellen (Wiese, Park ohne Müll): kleines Leckerli werfen und SUCH sagen.",
      "{dogName} sucht aktiv mit der Nase, statt zufällig aufzunehmen.",
      "Wiederhole 5-7 mal pro Spaziergang an verschiedenen Stellen.",
      "Steigere: zwei Leckerlis gleichzeitig, in verschiedene Richtungen.",
      "Variation: Leckerli unter Blätter oder ins hohe Gras werfen.",
      "{dogName} lernt: das aktive Suchen zahlt sich aus, das passive Aufnehmen wird zur Nebensache.",
      "Pro Spaziergang 1 Mal eine längere Mantrailing-Einheit (5-10 Min) einbauen.",
    ],
    phase: "generalisierung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// RECALL (unzuverlässiger Rückruf) — 7 Übungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: HIER positiv laden, Schleppleine als Sicherheits-
// Brücke, niemals fuer Negatives missbrauchen. Gradient: leicht → schwer.

const RECALL_EXERCISES: ExerciseTemplate[] = [
  {
    id: "r-hier-laden",
    title: "HIER positiv laden",
    shortDesc: "Das Signal muss für {dogName} der beste Moment seines Tages werden",
    intro: "Wenn HIER nicht 100% positiv ist, kommt {dogName} nicht zuverlässig. Wir laden HIER neu, mit absoluten Top-Belohnungen — Leberwurst, Hähnchen, Käse, nicht Trockenfutter.",
    steps: [
      "Wähle ein BESONDERES Wort als Recall-Signal. Falls HIER schon vergiftet ist (Hund kommt nicht), nimm KOMM-HER.",
      "Drinnen, wenn {dogName} entspannt ist: aus 3m Entfernung sage KOMM-HER in fröhlich-ruhigem Ton.",
      "{dogName} kommt: JACKPOT von 5 hochwertigen Leckerlis (Hähnchen) hintereinander gefüttert.",
      "Lass {dogName} dann sofort wieder gehen, ohne Forderung. Komm-Her endet nicht mit Anleinen oder Heim.",
      "5 Wiederholungen pro Session, 3 Sessions pro Tag drinnen.",
      "Über 1 Woche etabliert sich: KOMM-HER = bester Moment des Tages.",
      "Niemals KOMM-HER für Negatives nutzen: Bad, Tierarzt, Anleinen am Spaziergangsende. Da nimmst du ein anderes Wort.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "r-restraint-recall",
    title: "Restraint-Recall: Festhalte-Rückruf",
    shortDesc: "Klassisches Spiel für hohe Motivation und Sprintfreude",
    intro: "Bei diesem Spiel hält jemand {dogName} fest, du rennst weg und rufst dann KOMM-HER. Der Hund rennt mit hoher Energie und Motivation. Klassische Methode, funktioniert fast immer.",
    steps: [
      "Brauchst Helfer (Partner oder Familienmitglied).",
      "{dogName} ist beim Helfer, du gehst 10m weg in Sicht.",
      "Drehe dich um, gehe in tiefere Hocke.",
      "Rufe fröhlich KOMM-HER und gleichzeitig: Helfer lässt los.",
      "{dogName} sprintet zu dir.",
      "Bei Ankunft: GROßER Jackpot aus 5-7 Hähnchen-Stücken + überschwängliches Lob.",
      "Wiederhole 4-6 mal in einer Session.",
      "Steigere Distanz schrittweise auf 30-50m.",
      "Übertrage auf draußen mit Schleppleine als Sicherheit.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "r-schleppleine",
    title: "Schleppleinen-Arbeit",
    shortDesc: "5-10m Leine als Sicherheits-Brücke zwischen Hier-Drinnen und Freilauf",
    intro: "Bevor du Freilauf riskierst, üben wir mit 5-10m Schleppleine. {dogName} fühlt sich frei, du hast Notfall-Kontrolle. Die Brücke zwischen Drinnen-Training und Freilauf.",
    steps: [
      "Wähle eine 5-10m Schleppleine (Biothane, nicht Seil — Seil verbrennt die Hände).",
      "Trage Handschuhe falls {dogName} groß ist.",
      "An ruhigen Orten ohne andere Hunde, lass {dogName} auf Distanz schnüffeln.",
      "Rufe regelmäßig (alle 3-5 Min) KOMM-HER. Sicherheitsabstand kurz halten.",
      "{dogName} kommt: Jackpot von 5 Hähnchen-Stücken. Dann wieder gehen lassen, nicht festhalten.",
      "Falls {dogName} NICHT kommt: NICHT rufen wiederholen. Statt dessen Leine sanft Richtung dir aufnehmen, weiter zurückziehen bis {dogName} bei dir ist. Dann Jackpot trotzdem.",
      "{dogName} lernt: Kommen lohnt sich, Nicht-Kommen kostet Zeit aber ohne Drama.",
      "Über 2-3 Wochen Schleppleine wird zuverlässiger.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 30,
    suitableFor: {},
  },
  {
    id: "r-hier-mit-ablenkung",
    title: "KOMM-HER mit Ablenkung",
    shortDesc: "Steigerung: Recall klappt auch wenn was Interessanteres lockt",
    intro: "Hier wird der Recall erst echt: andere Hunde, Jogger, Wildgeruch. {dogName} lernt, dass die Belohnung beim Halter größer ist als die Ablenkung — wenn die Belohnung hoch genug ist.",
    steps: [
      "Mit Schleppleine an einem Ort mit moderater Ablenkung (Park-Rand, anderer Hund in 30m).",
      "{dogName} schnüffelt oder schaut die Ablenkung. Du rufst KOMM-HER fröhlich.",
      "Falls {dogName} kommt: SUPER-JACKPOT von 7-10 Hähnchen-Stücken + 1 Min Lobeshymne.",
      "Falls {dogName} NICHT kommt: ruhig zurückziehen mit Schleppleine, KEINE Wiederholung des Signals.",
      "{dogName} bei dir: trotzdem 3 Leckerlis (kleinere Belohnung, aber positive Reaktion).",
      "Pro Spaziergang 4-6 Recall-Versuche unter Ablenkung.",
      "Steigerung über 2-4 Wochen: stärkere Ablenkungen, kürzere Distanz zum Reiz.",
      "Wichtig: 80% Erfolgsrate halten. Wenn weniger: Ablenkung reduzieren, nicht Druck erhöhen.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 15,
    suitableFor: {},
  },
  {
    id: "r-pfeife-aufbauen",
    title: "Hundepfeife als zweites Signal",
    shortDesc: "Pfeife trägt weit, klingt immer gleich, kann nicht 'vergiftet' werden",
    intro: "Eine Hundepfeife ist das beste Recall-Backup: trägt 200m+, ist immer gleich (nicht wie deine Stimme die Frust-getönt sein kann), und du kannst sie frisch konditionieren.",
    steps: [
      "Kaufe eine ACME 211.5 oder ähnliche Hunde-Pfeife.",
      "Drinnen: pfeife einen klaren Doppelton (kurz-kurz oder lang-kurz), sofort Jackpot.",
      "Wiederhole 5-7 mal pro Session, 2 Sessions täglich, eine Woche lang.",
      "Übertrage nach draußen mit Schleppleine: Pfeifen-Signal + Jackpot bei Ankunft.",
      "Pfeife wird zum Garantie-Recall, KOMM-HER bleibt der normale Alltags-Recall.",
      "Pfeife darf NIEMALS für Negatives genutzt werden (Anleinen, Heim).",
      "Nach 4 Wochen ist die Pfeife zuverlässiger als jede Stimme.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "r-freilauf-erste",
    title: "Erster Freilauf in sicherer Zone",
    shortDesc: "Die Schleppleine fällt — aber kontrolliert, mit klaren Sicherheits-Bedingungen",
    intro: "Wenn KOMM-HER unter Ablenkung 90%+ sitzt, ist der erste Freilauf reif. Aber nur in einer eingezäunten oder topographisch sicheren Zone, und nur in moderater Reiz-Phase.",
    steps: [
      "Wähle die sicherste Zone die du kennst: eingezäunte Hundewiese, Waldlichtung weit weg von Straße.",
      "Zeitlich: wenig andere Hunde, gute Sicht.",
      "Schleppleine ablegen lassen, NICHT abnehmen — {dogName} darf 10m laufen, dann KOMM-HER.",
      "Bei zuverlässigem Recall innerhalb von 5 Sekunden: weiter machen.",
      "Bei Nicht-Kommen: SOFORT zurück zur Schleppleine, weitere 2 Wochen üben.",
      "Pro Freilauf max 15-20 Min, niemals länger.",
      "Beende Freilauf IMMER bei einem perfekten Recall, niemals nach einem Fehler.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 20,
    suitableFor: {},
  },
  {
    id: "r-emergency-recall",
    title: "Notfall-Recall: das letzte Wort",
    shortDesc: "Ein Signal, das NIEMALS für etwas Normales genutzt wird — nur Notfall",
    intro: "Der Notfall-Recall ist ein Sonderfall: ein einziges Wort (z.B. STOP-HER oder ein Pfiff), das du NUR in echten Notfällen einsetzt. Weil es so selten genutzt wird, ist die Belohnung astronomisch und {dogName} kommt zu 100%.",
    steps: [
      "Wähle ein Wort/Pfeife, das du sonst niemals nutzt.",
      "Konditioniere drinnen mit MEGA-Belohnung: einem Stück echtem Rinderfilet, das {dogName} sonst nie bekommt.",
      "Sage Signal, gib MEGA-Belohnung. 2 mal pro Tag, eine Woche lang. KEINE Wiederholung.",
      "Übertrage nach draußen: nur ALLE 1-2 Wochen einmal, mit MEGA-Belohnung.",
      "Wenn du das Signal in einer Notfall-Situation einsetzt: {dogName} kommt. Die Verknüpfung ist so stark wegen seltenheit + extremer Belohnung.",
      "Wichtig: NIEMALS für normale Recalls nutzen, sonst verliert es seine Magie.",
      "Belohnung muss IMMER stattfinden, auch wenn du gerade in Panik bist.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 3,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// BARKING (uebermaessiges Bellen) — 7 Uebungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: erst Trigger identifizieren, dann RUHE belohnen statt
// Bellen bestrafen. Tuerklingel = Decken-Routine, Frust-Bellen = Ignorieren,
// reaktives Bellen = Counter-Conditioning. Niemals anschreien.

const BARKING_EXERCISES: ExerciseTemplate[] = [
  {
    id: "b-trigger-tagebuch",
    title: "Trigger-Tagebuch: was lost das Bellen aus?",
    shortDesc: "Bevor du trainierst, brauchst du Daten: wann, was, wie lang bellt {dogName}?",
    intro: "Bellen hat immer einen Grund. Aufregung, Frust, Angst, Aufmerksamkeit. Erst wenn du die Trigger kennst, kannst du gezielt arbeiten. Diese Woche dokumentierst du eine Woche lang.",
    steps: [
      "Lege ein kleines Notizheft an, eine Woche lang dabei.",
      "Bei jedem Bell-Vorfall notiere: Uhrzeit, Ort, Auslöser (Klingel, Hund vorbei, Frust...), Dauer.",
      "Notiere auch deine Reaktion: hingegangen? Geschimpft? Ignoriert?",
      "Nach 7 Tagen: schau dir die Liste an. Gibt es Muster?",
      "Identifiziere deine TOP-3-Trigger.",
      "Diese 3 werden dein Trainings-Fokus.",
      "Trigger ohne Daten ist Stochern im Nebel.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "b-ruhe-marker",
    title: "RUHE-Marker etablieren",
    shortDesc: "Belohne das SCHWEIGEN, nicht das Anschreien des Bellens",
    intro: "Statt das Bellen zu bestrafen, belohnen wir konsequent Phasen ohne Bellen. {dogName} lernt: still sein lohnt sich. Das ist die Basis fuer alles Weitere.",
    steps: [
      "Beobachte {dogName} bewusst. Sobald 5 Sekunden Stille (nicht bellt, nicht jault): leise FEIN sagen und Leckerli geben.",
      "Erst 5 Sek, dann 10, dann 20, dann 30, dann 1 Min.",
      "Belohnung kommt LEISE und RUHIG. Keine grosse Sache.",
      "Sage NIEMALS 'leise' oder 'still' in dieser Phase — wir bauen den Marker um Stille, nicht um ein Stop-Signal.",
      "Pro Tag 8-10 dieser Mini-Belohnungen.",
      "Ueber 2 Wochen lernt {dogName}: Stille = manchmal kommt was Gutes.",
      "Niemals anschreien wenn {dogName} bellt, das ist fuer den Hund auch Aufmerksamkeit.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "b-tuerklingel-decke",
    title: "Tuerklingel-Routine: Klingel = Decke",
    shortDesc: "Bei Klingelton geht {dogName} ruhig auf die Decke",
    intro: "Wenn Klingelbellen Thema ist, etablierst du eine Alternative: bei Klingel rennt {dogName} nicht zur Tuer, sondern auf die Decke. Pavlov-Konditionierung pur.",
    steps: [
      "{dogName} muss vorher Decke gut kennen (Entspannungsdecke-Uebung).",
      "Spiele Klingel-Aufnahme leise vom Handy ab.",
      "Sage sofort PLATZ, locke {dogName} auf die Decke.",
      "Belohne mit hochwertigem Leckerli auf der Decke.",
      "10 Wiederholungen pro Session, 2 Sessions taeglich.",
      "Steigere Klingel-Lautstaerke ueber 2 Wochen.",
      "Dann echte Klingel mit Helfer: jemand klingelt von draussen.",
      "{dogName} rennt auf Decke: JACKPOT von 5 Leckerlis.",
      "Klingel ohne Decke nicht mehr akzeptieren — konsequent.",
    ],
    phase: "fundament",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "b-counter-cond-aussen",
    title: "Counter-Conditioning bei Aussenreizen",
    shortDesc: "Hund vorbei = Leckerli, nicht Bellen-Auslöser",
    intro: "Wenn {dogName} an Fenster oder im Garten bellt: aenderung der emotionalen Verknüpfung. Reiz auftauchen = Leckerli kommt. Reiz weg = Leckerli weg. Mit Konsistenz aendert sich die Reaktion.",
    steps: [
      "An typischer Bell-Position (Fenster, Garten): warte bis ein Reiz auftaucht (Hund vorbei, Postbote).",
      "BEVOR {dogName} bellen kann: SCHAU sagen und Leckerli geben.",
      "Solange Reiz sichtbar ist, durchgehend fuettern.",
      "Reiz weg: Leckerli stop.",
      "Wichtig: das funktioniert NUR wenn du den Reiz frueh genug siehst.",
      "Falls {dogName} schon bellt: zu spaet. Distanz vergroessern (Fenster zu, in anderen Raum).",
      "Ueber Wochen lernt {dogName}: Reiz = positive Erwartung, nicht Bellen.",
      "Belohnungs-Frequenz erst nach 4 Wochen reduzieren.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "b-aufmerksamkeits-bellen",
    title: "Aufmerksamkeits-Bellen: konsequent ignorieren",
    shortDesc: "Wenn {dogName} dich anbellt um was zu kriegen: Ruecken zudrehen",
    intro: "Manche Hunde bellen um Aufmerksamkeit, Spiel oder Futter zu kriegen. Das funktioniert NUR wenn es funktioniert. Konsequent ignorieren = das Bellen verschwindet ueber 2-3 Wochen.",
    steps: [
      "Identifiziere klar: bellt {dogName} um was von DIR zu wollen (anschauen, fuettern, spielen)?",
      "Bei diesem Belltyp: SOFORT Ruecken zudrehen, ohne Worte.",
      "Verlasse den Raum wenn moeglich.",
      "Komm zurueck wenn {dogName} 30 Sek ruhig war.",
      "Beim Ruhigwerden: FEIN + Leckerli, aber leise.",
      "Wichtig: Konsistenz ist alles. EINE Belohnung beim Bellen sabotiert 2 Wochen Arbeit.",
      "Extinktions-Burst: in Tag 3-7 wird Bellen erst INTENSIVER, dann verschwindet es.",
      "Halte aus. Wer nachgibt, lernt {dogName}: Bellen MUSS nur intensiver werden.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "b-frust-management",
    title: "Frust-Bellen: Frust-Toleranz aufbauen",
    shortDesc: "Wenn {dogName} aus Frust bellt, hilft nur Frust-Toleranz lehren",
    intro: "Manche Hunde bellen weil sie was nicht kriegen oder nicht koennen. Ein Eichhoernchen ausser Reichweite, ein anderer Hund unerreichbar. Die Loesung: Frust-Toleranz systematisch aufbauen.",
    steps: [
      "Setze {dogName} bewusst kleinen Frust-Momenten aus: vor Futter WARTE sagen, vor Spielzeug WARTE.",
      "Steigere die Wartezeit langsam: 5 Sek, 10, 20, 30.",
      "Bei Bellen waehrend WARTE: nicht aufloesen, Hand zurueckziehen.",
      "Erst wenn 3 Sek ruhig: Aufloesung und Belohnung.",
      "Pro Tag 5-7 solche Mini-Frust-Situationen.",
      "Ueber Wochen lernt {dogName}: Frust kann ich aushalten, das Bellen bringt nichts.",
      "Niemals laut werden bei Frust-Bellen — verstaerkt die Aufregung.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "b-laeuten-routine",
    title: "Echte Klingel-Routine im Alltag",
    shortDesc: "Klingel = Decke = Belohnung, auch bei echten Besuchen",
    intro: "Wenn die Tuerklingel-Decke-Routine drinnen sitzt, testen wir mit echten Besuchen. {dogName} bleibt auf der Decke, bis du das OK-Signal gibst.",
    steps: [
      "Vorher: Helfer kommt zu Besuch. Du bist vorbereitet.",
      "Klingel: {dogName} sollte automatisch zur Decke laufen.",
      "Du oeffnest die Tuer, begruesst leise.",
      "Besuch kommt rein, achtet {dogName} nicht.",
      "{dogName} bleibt auf Decke: alle 30 Sek Leckerli.",
      "Nach 5 Min mit ruhigem {dogName}: OK-Signal, sie darf vorsichtig hallo sagen.",
      "Falls {dogName} von der Decke geht: ruhig zurueckfuehren, ohne Drama.",
      "Ueber Wochen wird Klingel zur normalen Routine, nicht zum Bell-Auslöser.",
    ],
    phase: "generalisierung",
    difficulty: "medium",
    durationMin: 15,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// ANXIETY (Trennungsangst) — 7 Uebungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: graduell aufbauen von Sekunden zu Stunden, KEIN
// Drama beim Gehen/Kommen, Kong als Verknuepfung, Trigger-Stack lesen.
// Bei schwerer Trennungsangst eventuell Tierarzt fuer medizinische Unterstuetzung.

const ANXIETY_EXERCISES: ExerciseTemplate[] = [
  {
    id: "ax-trigger-stack",
    title: "Abschieds-Trigger-Stack erkennen",
    shortDesc: "Welche Vorboten kennt {dogName}? Schluessel, Schuhe, Jacke?",
    intro: "Hunde mit Trennungsangst fangen oft schon an zu stressen BEVOR du gehst. Sie lesen Trigger: Schluessel, Schuhe, Jacke, Computer ausschalten. Diese Woche identifizierst du den Trigger-Stack.",
    steps: [
      "Beobachte {dogName} 3-5 Tage genau, wenn du das Haus verlaesst.",
      "Notiere: ab welchem Moment veraendert sich das Verhalten? Atmung schneller? Lecken? Hecheln?",
      "Identifiziere den Trigger-Stack: typischerweise Schluessel + Schuhe + Tasche + Jacke + Tuer-Hand.",
      "Diese Trigger werden wir in Woche 2 entkoppeln.",
      "Bewusstheit ist 50% der Loesung.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "ax-trigger-entkoppeln",
    title: "Trigger entkoppeln: Schluessel ohne Gehen",
    shortDesc: "Schluessel nehmen, dann wieder hinlegen. {dogName} lernt: das hat keine Bedeutung mehr",
    intro: "Wir entkoppeln die Vorboten vom Gehen. {dogName} sieht Schluessel = nichts passiert. Sieht Schuhe an = nichts passiert. Ueber Wochen verlieren die Trigger ihre angst-ausloesende Wirkung.",
    steps: [
      "10x am Tag Schluessel nehmen, in der Hand halten, hinlegen. Nicht gehen.",
      "10x Schuhe anziehen, ein paar Schritte, ausziehen. Nicht gehen.",
      "10x Tuerklinke beruehren, drehen, loslassen. Nicht gehen.",
      "{dogName} schaut interessiert, dann verliert sie Interesse.",
      "Genau das ist der Lerneffekt: Trigger = bedeutungslos.",
      "Ueber 1-2 Wochen verlieren die Trigger ihre Wirkung.",
      "Wichtig: NICHT trainings-aehnlich machen, sondern beilaeufig in deinem Alltag einbauen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "ax-mini-sekunden",
    title: "Allein-Sein in Sekunden aufbauen",
    shortDesc: "Beginne mit 2 Sekunden, steigere zu Stunden — ueber Wochen",
    intro: "Allein-bleiben wird wie ein Muskel trainiert. 2 Sekunden, 5, 10, 30, 1 Min, 5 Min. Wer zu schnell steigert, baut die Angst wieder auf. Geduld ist das ganze Spiel.",
    steps: [
      "Tag 1: {dogName} ist im Wohnzimmer, du gehst 2 Sek aus dem Raum, kommst zurueck. Wiederhole 10x.",
      "Tag 2: 5 Sek. Tag 3: 10 Sek. Tag 4: 30 Sek. Tag 5: 1 Min. Tag 6-7: 2-3 Min.",
      "Niemals dramatisch verabschieden oder begruessen.",
      "Beim Zurueckkommen: ruhig, kein 'Hallo mein Schatz!'.",
      "Falls {dogName} jault oder bellt: zurueck zur letzten erfolgreichen Stufe.",
      "Niemals erst bei Stress-Reaktion zurueckkommen, sonst lernt {dogName}: jaulen = Halter kommt.",
      "Komm zurueck wenn {dogName} ruhig ist, idealerweise schon vor dem ersten Stress-Anzeichen.",
    ],
    phase: "fundament",
    difficulty: "medium",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "ax-kong-beim-gehen",
    title: "Kong als positive Verknuepfung beim Gehen",
    shortDesc: "Du gehst = der beste Kong des Tages kommt",
    intro: "{dogName} bekommt ihren Lieblings-Kong NUR wenn du gehst. Damit wird das Gehen positiv verknuepft. Halter weg = Lieblings-Snack da.",
    steps: [
      "Stopfe einen Kong besonders gut: Hueh Tneraserstreifen, eingefroren ist schwerer.",
      "Kurz BEVOR du gehst: gib Kong an einem festen Platz (Decke oder Korb).",
      "Geh ohne Drama raus.",
      "Komm zurueck nach (anfangs) 2 Sek bis (spaeter) Stunden.",
      "Kong wegnehmen sobald du zurueck bist. Er ist NUR fuer die Abwesenheit reserviert.",
      "Wenn {dogName} den Kong noch nicht angefangen hat: Stress-Indikator. Zeit reduzieren.",
      "Wenn {dogName} ruhig kaut waehrend du gehst: Erfolg.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "ax-sicherheits-decke",
    title: "Sicherheits-Decke als mobiler Anker",
    shortDesc: "Eine Decke wird zum vertrauten Ort, auch wenn du nicht da bist",
    intro: "Die Entspannungsdecke wird zum Sicherheits-Anker. {dogName} verbringt Allein-Zeit auf der Decke. Pawlow-Konditionierung: Decke = Sicherheit + Ruhe.",
    steps: [
      "Decke muss vorher als Ruhe-Anker etabliert sein.",
      "Beim Verlassen: lege {dogName} auf die Decke, gib den Kong.",
      "Die Decke liegt am festen Platz, idealerweise mit Sichtschutz (Korb, Hundesofa).",
      "Wenn {dogName} hochsteht: ruhig zurueckfuehren, dann weiter.",
      "Ueber Zeit wird die Decke zur 'Allein-Zeit-Insel'.",
      "Reisetasche-Version: wenn du laenger weg bist, kann eine getragene Decke (mit deinem Geruch) zusaetzlich helfen.",
    ],
    phase: "steigerung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "ax-langzeit-aufbau",
    title: "Stunden-Phasen vorsichtig aufbauen",
    shortDesc: "Von 30 Min auf 4 Stunden — schrittweise, mit Video-Beobachtung",
    intro: "Wenn die kurzen Phasen sitzen, baust du langsam Stunden auf. Wichtig: per Video kontrollieren, was {dogName} macht waehrend du weg bist. Nicht raten.",
    steps: [
      "Installiere eine Smartphone-Webcam oder Smart-Camera, die dir Live-Streaming gibt.",
      "Beginne mit 30 Min Abwesenheit, beobachte per Video.",
      "Kriterien: schlaeft sie? Kont sie ihren Kong ruhig? Lauft sie aufgeregt?",
      "Wenn ruhig: naechste Stufe 45 Min, 1h, 90 Min, 2h.",
      "Wenn Stress: zurueck zur letzten erfolgreichen Stufe, dort 1 Woche bleiben.",
      "Zielwert: 4 Stunden ruhige Allein-Zeit. Mehr ist auch fuer ausgeglichene Hunde grenzwertig.",
      "Bei schwerer Trennungsangst: Tierarzt einbeziehen. Manchmal hilft medizinische Unterstuetzung.",
    ],
    phase: "generalisierung",
    difficulty: "hard",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "ax-tagesroutine",
    title: "Berechenbare Tagesroutine etablieren",
    shortDesc: "Trennungsangst sinkt mit vorhersehbarer Struktur",
    intro: "Hunde mit Trennungsangst profitieren massiv von berechenbaren Tagesablaeufen. Gleicher Spaziergang-Zeitpunkt, gleiche Fuetterungs-Zeit, gleiche Allein-Zeiten. Unsicherheit reduzieren.",
    steps: [
      "Etabliere feste Zeiten fuer Spaziergang, Fuetterung, Beschaeftigung, Allein-Zeit.",
      "Schreibe sie an den Kuehlschrank.",
      "Auch am Wochenende einhalten — Hunde unterscheiden nicht zwischen Wochenende und Werktag.",
      "Vor jeder Allein-Zeit: 15-20 Min Beschaeftigung (Spaziergang, Suchspiel).",
      "Mueder Hund + berechenbare Struktur = halbierte Trennungsangst.",
      "Ueber 4-6 Wochen wird die Routine internalisiert.",
    ],
    phase: "generalisierung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// JUMPING (Anspringen) — 6 Uebungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: 4 Pfoten auf dem Boden = Belohnung. Beim Springen
// konsequent Aufmerksamkeit entziehen. SITZ als Alternativ-Verhalten
// bei Begegnungen, Decken-Routine bei Besuch.

const JUMPING_EXERCISES: ExerciseTemplate[] = [
  {
    id: "j-vier-pfoten-belohnen",
    title: "4 Pfoten auf dem Boden = Belohnung",
    shortDesc: "Das wichtigste Prinzip: nur ruhiges Stehen kriegt Aufmerksamkeit",
    intro: "Hunde, die anspringen, lernen ueber Wochen das Gegenteil: 4 Pfoten auf dem Boden bringen Belohnung, Springen bringt NICHTS. Konsequenz ueber 2-3 Wochen wirkt.",
    steps: [
      "Bei jedem Wieder-Sehen (kommst nach Hause, in den Raum): {dogName} hat 4 Pfoten am Boden? Sofort runter, ruhig hallo sagen, leise Streicheln.",
      "Sobald sie hochspringt: Ruecken zudrehen, ignorieren, kein Augenkontakt.",
      "4 Pfoten zurueck am Boden: sofort wieder zuwenden.",
      "Sie springt wieder: Ruecken zudrehen.",
      "{dogName} lernt: Springen = du gehst weg. Stehen = ich kriege Hallo.",
      "Konsistenz ist ALLES. Ein Familienmitglied der einmal nachgibt, sabotiert die Arbeit.",
      "Ueber 2-3 Wochen verschwindet das Anspringen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "j-sitz-als-gruess",
    title: "SITZ als Begruessungs-Alternative",
    shortDesc: "{dogName} soll SITZ als Begruessungs-Verhalten lernen",
    intro: "Statt nur Springen zu unterbinden, geben wir {dogName} eine Alternative: SITZ ist die neue Begruessung. Bei Begegnung sitzt sie, kriegt dafuer Aufmerksamkeit.",
    steps: [
      "SITZ-Signal muss vorher zuverlaessig sitzen.",
      "Bei Begegnungen (Familie, Gaeste, Spaziergaenger): SITZ sagen.",
      "{dogName} sitzt: sofort FEIN + Streicheln + Leckerli.",
      "Sie steht auf zum Springen: Streicheln stop, Ruecken zudrehen.",
      "Sobald wieder SITZ: zuwenden.",
      "Ueber Wochen wird SITZ zur automatischen Begruessungs-Routine.",
      "Auch Gaeste anweisen: nur wenn {dogName} sitzt, darf sie sie streicheln.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "j-tuergaeste-routine",
    title: "Gaeste-Begruessungs-Routine etablieren",
    shortDesc: "Bei Klingel: {dogName} geht auf die Decke und wartet",
    intro: "Aehnlich wie bei Bellen: Klingel = Decke. {dogName} wartet auf der Decke, bis du den Gast hereingelassen hast und ihr OK-Signal gibst.",
    steps: [
      "Vorher: Decke und Tuerklingel-Routine muessen sitzen.",
      "Klingel: {dogName} auf Decke fuehren (oder von selbst dort).",
      "Tuer oeffnen, Gast hereinbitten, Schuhe ausziehen.",
      "Gast achtet {dogName} nicht.",
      "{dogName} bleibt auf Decke: alle 30 Sek Leckerli.",
      "Nach 3-5 Min ruhigem {dogName}: OK-Signal, sie darf vorsichtig hallo sagen.",
      "Gast streichelt nur wenn {dogName} sitzt — NICHT bei Springen.",
      "Ueber Wochen wird Gaeste-Empfang routiniert.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 15,
    suitableFor: {},
  },
  {
    id: "j-spazier-vorbeigaenger",
    title: "Vorbeigaenger draussen: SITZ statt Anspringen",
    shortDesc: "Wenn Menschen entgegen kommen, sitzt {dogName} an der Bein-Position",
    intro: "Anspringen draussen ist heikel: nicht jeder Mensch will hochgesprungen werden. Wir etablieren: bei Vorbeigaengern setzt sich {dogName} an deine Bein-Position.",
    steps: [
      "Sobald {dogName} einen Vorbeigaenger sieht (15m+ Distanz): SITZ neben deinem Bein.",
      "Belohne mit Leckerli waehrend sie sitzt.",
      "Vorbeigaenger geht vorbei.",
      "Nach Passage: FEIN und weiter.",
      "Wichtig: Vorbeigaenger anweisen, dass sie {dogName} NICHT anschauen oder ansprechen sollen wenn sie sitzt.",
      "Ueber Wochen wird Sitzen die normale Reaktion auf vorbeikommende Menschen.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "j-konsistenz-familie",
    title: "Konsistenz in der Familie: alle ziehen mit",
    shortDesc: "Das ganze Haushalt muss dieselbe Regel anwenden",
    intro: "Anspringen ist ein Konsistenz-Problem. Wenn 1 Familienmitglied das Springen erlaubt oder belohnt, sabotiert es die ganze Arbeit. Diese Woche etablierst du Familien-Konsistenz.",
    steps: [
      "Erklaere allen Familienmitgliedern die Regel: 4 Pfoten = Hallo, Springen = ignorieren.",
      "Auch Kindern (so weit altersgerecht): nicht streicheln waehrend Hund springt.",
      "Auch Gaesten: 'Bitte ignoriere ihn wenn er springt'.",
      "Schreibe die Regel an einen Zettel am Eingang, fuer Gaeste sichtbar.",
      "Ueber 2-3 Wochen Konsistenz verschwindet das Anspringen.",
      "1 Inkonsistenz pro Woche kostet 1 Woche Trainingsfortschritt.",
    ],
    phase: "generalisierung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "j-wartungs-routine",
    title: "Wartungs-Routine: Begruessungen ueben",
    shortDesc: "Auch nach 8 Wochen weiter aktiv Begruessungen ueben",
    intro: "Anspringen kann zurueckkommen, wenn die Belohnungsstruktur verschwindet. Etabliere eine Wartungs-Routine: 1x taeglich bewusst Begruessungen ueben.",
    steps: [
      "Pro Tag: 1 bewusste Begruessungs-Uebung. Gehe aus dem Raum, komm zurueck.",
      "Belohne SITZ bei Begruessung mit FEIN + Leckerli.",
      "Bei Springen: konsequent ignorieren.",
      "Aktiv kleine Sessions, statt zu hoffen dass es bleibt.",
      "Alle 2-3 Wochen einen 'Stress-Test': neue Person kommt zu Besuch, beobachten was passiert.",
      "Bei Rueckfall: 1 Woche Konsequenz, dann ist wieder gut.",
    ],
    phase: "generalisierung",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// DESTRUCTIVE (Zerstoerungsverhalten) — 7 Uebungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: erst Ursache klaeren (Langeweile? Trennungsangst?
// Beissduerfnis?). Erlaubte Kau-Objekte etablieren, Management bei
// Abwesenheit, mentale Auslastung erhoehen.

const DESTRUCTIVE_EXERCISES: ExerciseTemplate[] = [
  {
    id: "d-ursachen-analyse",
    title: "Ursachen-Analyse: warum zerstoert {dogName}?",
    shortDesc: "Bevor du trainierst, klaere die Wurzel — Langeweile, Angst, Beissduerfnis?",
    intro: "Zerstoerung hat verschiedene Ursachen, die voellig unterschiedliche Loesungen brauchen. Diese Woche identifizierst du den Hauptgrund.",
    steps: [
      "Was wird zerstoert? Schuhe (Geruch-orientiert)? Moebel (Beissduerfnis)? Tueren (Trennungsangst)?",
      "WANN wird zerstoert? Nur in deiner Abwesenheit (Trennungsangst)? Auch wenn du da bist (Langeweile/Beissduerfnis)?",
      "WIE alt ist {dogName}? Junge Hunde (4-9 Monate) sind oft im Zahnwechsel — Beissduerfnis.",
      "Welche Auslastung kriegt {dogName}? Wenig Auslastung = Langeweile.",
      "Notiere 1 Woche lang: was, wann, wie?",
      "Basierend auf der Analyse waehlst du Schwerpunkt: Anti-Langeweile, Anti-Trennungsangst, oder Beissduerfnis-Management.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "d-kauobjekte-etablieren",
    title: "Erlaubte Kau-Objekte etablieren",
    shortDesc: "Klare Liste was {dogName} kauen darf — und Rotation",
    intro: "{dogName} hat ein Beissduerfnis, das gestillt werden muss. Statt es zu unterdruecken, kanalisieren wir es in ERLAUBTE Objekte. 4-5 verschiedene, in Rotation.",
    steps: [
      "Investiere in 4-5 verschiedene Kau-Objekte: Naturkauartikel (Bueffelhaut, Ochsenziemer), Kong, Schnueffelmatte, Holzknochen, Geweih.",
      "Lege NICHT alle gleichzeitig hin — Rotation.",
      "Pro Tag 1-2 verschiedene Objekte verfuegbar, andere weglegen.",
      "{dogName} lernt: 'Mein Sortiment ist interessant.'",
      "Lange Kau-Sessions (15-30 Min) reduzieren den Kau-Druck massiv.",
      "Verbotenes Objekt (Schuh): sofort Tausch mit erlaubtem Objekt.",
      "Niemals 'Pfui' rufen ohne Alternative — das verstaerkt den Tausch-Trieb.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "d-management-zonen",
    title: "Management: Sichere Zonen etablieren",
    shortDesc: "{dogName} hat keinen Zugang zu zerstoerbaren Sachen wenn unbeobachtet",
    intro: "Solange das Training nicht steht, hilft Management. {dogName} hat keine Moeglichkeit, Schuhe oder Moebel zu zerstoeren — weil sie nicht erreichbar sind.",
    steps: [
      "Identifiziere die Risiko-Zonen: Flur mit Schuhen, Wohnzimmer mit Fernseher-Kabel, Buero mit Papier.",
      "Bei deiner Abwesenheit oder Unbeobachtetheit: {dogName} in einer sicheren Zone (Box, Kueche mit Babyschutz).",
      "In dieser sicheren Zone: ihre erlaubten Kau-Objekte + Wassernapf.",
      "Niemals als Strafe nutzen — das ist eine Sicherheits-Zone, kein Gefaengnis.",
      "Ueber Zeit wird die Zone zur Lieblings-Ruhezone.",
      "Auch bei Anwesenheit: lieber Tueren zu, statt Hund frei in Risiko-Bereiche zu lassen.",
      "Management ist kein Aufgeben — es ist verantwortungsvolles Vorgehen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "d-langeweile-auslasten",
    title: "Anti-Langeweile: Kopf + Nase + Bewegung",
    shortDesc: "Ein unterforderter Hund zerstoert. Loesung: Auslastung verdoppeln",
    intro: "Falls Langeweile die Ursache ist (oft bei jungen Hunden + wenig Auslastung): die Mischung machts. Bewegung + Kopfarbeit + Nasenarbeit, nicht nur Bewegung.",
    steps: [
      "Erstelle einen Auslastungsplan: pro Tag 1 Spaziergang (30-60 Min mit Tempo-Wechseln), 1 Nasenarbeit (Suchspiel), 1 Kopfarbeit (Trick, Kong).",
      "Falls {dogName} jung ist (4-9 Monate): wenig stumpfes Toben, viel Kopfarbeit.",
      "Falls {dogName} erwachsen ist: mehr Mantrailing draussen, das beruhigt nachhaltig.",
      "Pro Tag 30-60 Min Beschaeftigungs-Tools (Kong, Schnueffelmatte) als Mahlzeit-Ersatz.",
      "Nach 1-2 Wochen guter Auslastung verschwindet Langeweile-Zerstoerung.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "d-tausch-statt-strafe",
    title: "Tausch statt Strafe bei verbotenen Objekten",
    shortDesc: "{dogName} hat Schuh im Maul: ruhig Tausch, kein Drama",
    intro: "Wenn du {dogName} mit einem verbotenen Objekt erwischt, ist Strafe kontraproduktiv. Tausch ist die richtige Reaktion: ruhig naehern, Leckerli anbieten, Tausch.",
    steps: [
      "{dogName} hat verbotenes Objekt: NICHT schreien, NICHT hinterherrennen.",
      "Hole hochwertiges Leckerli, naehere dich ruhig.",
      "AUS sagen, Leckerli hochhalten.",
      "{dogName} laesst los: FEIN + Leckerli + erlaubtes Kau-Objekt anbieten.",
      "Verbotenes Objekt wegraeumen, ohne Drama.",
      "Niemals das verbotene Objekt zurueckgeben — Tausch ist echt.",
      "Niemals hinterher schimpfen — {dogName} kann das nicht mit der vorigen Tat verknuepfen.",
    ],
    phase: "steigerung",
    difficulty: "easy",
    durationMin: 5,
    suitableFor: {},
  },
  {
    id: "d-allein-zeit-kong",
    title: "Allein-Zeit-Kong: 30 Min Beschaeftigung beim Gehen",
    shortDesc: "Vor jeder Abwesenheit ein gut gestopfter Kong als Beschaeftigung",
    intro: "Falls {dogName} aus Trennungsangst oder Langeweile waehrend deiner Abwesenheit zerstoert, hilft ein gut gestopfter Kong. 30 Minuten Beschaeftigung = oft die kritische Phase.",
    steps: [
      "Stopfe Kong dicht mit Nassfutter, eingefroren ist es 30+ Minuten Beschaeftigung.",
      "Variante: Schnueffelmatte mit Trockenfutter, dauert 20-30 Min.",
      "Vor jeder Abwesenheit gibst du den Kong ruhig.",
      "Geh ohne Drama raus.",
      "Komm zurueck nach (anfangs kurzer, dann laengerer) Zeit.",
      "Kong nehmen, wenn {dogName} noch arbeitet — er ist exklusiv fuer die Abwesenheit.",
      "Ueber Wochen wird Allein-Zeit positiv verknuepft mit Lieblings-Snack.",
    ],
    phase: "generalisierung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "d-langzeit-wartung",
    title: "Langzeit-Wartung: weiter unterhalb der Reizschwelle",
    shortDesc: "Auch nach 6 Monaten: Auslastung + Kau-Objekt-Rotation",
    intro: "Zerstoerung kann zurueckkommen, wenn die Bedingungen sich aendern: weniger Auslastung, andere Stress-Faktoren. Wartung ueber Monate noetig.",
    steps: [
      "Beibehalten: 4-5 Kau-Objekte in Rotation.",
      "Beibehalten: tägliche Auslastung mit Mischung.",
      "Beobachten: zerstoert {dogName} ploetzlich wieder? Was hat sich geaendert?",
      "Stress-Faktor checken: neue Wohnung, weniger Spaziergaenge, andere Routine?",
      "Bei Rueckfall: 1-2 Wochen wieder enger fuehren, Auslastung erhoehen.",
      "Management bleibt sinnvoll: lieber Tueren zu in Risiko-Phasen.",
    ],
    phase: "generalisierung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// SOILING (Stubenunreinheit) — 6 Uebungen
// ════════════════════════════════════════════════════════════════════
// Trainer-Mindset: haeufige Toilettenrunden, an richtigem Platz
// belohnen, Trigger erkennen (schnueffeln, drehen). Bei Welpen NORMAL,
// bei erwachsenen Hunden oft medizinisch oder stress-bedingt.

const SOILING_EXERCISES: ExerciseTemplate[] = [
  {
    id: "s-toiletten-routine",
    title: "Berechenbare Toiletten-Routine etablieren",
    shortDesc: "Feste Zeiten, feste Plaetze — der Hund lernt am schnellsten ueber Vorhersehbarkeit",
    intro: "Stubenreinheit baut sich ueber feste Routinen auf. {dogName} muss wissen: jetzt ist Toiletten-Zeit, hier ist der Ort. Vorhersehbarkeit beschleunigt den Lernprozess massiv.",
    steps: [
      "Pro Tag mindestens 5-7 Toilettenrunden: morgens, nach Mahlzeiten, nach Schlaf, abends, vor dem Schlafen.",
      "Bei jungen Hunden bzw. unreinen Hunden: alle 1-2 Stunden raus.",
      "Immer am selben Ort, gleicher Weg.",
      "Lasse {dogName} 5-10 Min Zeit zum Erledigen.",
      "Sobald {dogName} loslaesst: leise FEIN, hochwertiges Leckerli direkt am Platz.",
      "Niemand schimpfen wenn nichts kommt — geduldig warten.",
      "Notiere 1 Woche lang: wann passiert was? Dann kannst du Routine anpassen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 10,
    suitableFor: {},
  },
  {
    id: "s-belohnen-am-platz",
    title: "Belohnen genau am richtigen Platz",
    shortDesc: "Belohnung KOMMT am Ort des Geschehens — Timing entscheidet",
    intro: "Belohnung muss DIREKT am richtigen Platz und SOFORT nach dem Loslassen kommen. Bei Verzoegerung von 5+ Sekunden lernt {dogName} nichts. Timing ist alles.",
    steps: [
      "Habe immer Leckerlis dabei waehrend Toilettenrunden.",
      "{dogName} laesst los: WAEHREND sie laeuft, leise FEIN. NICHT erst nachdem sie fertig ist.",
      "Sobald sie fertig ist: SOFORT Leckerli direkt am Platz geben.",
      "Lobwort kann ergaenzt werden, aber Leckerli ist staerker.",
      "Niemals zu spaet belohnen — die Verknuepfung muss eng sein.",
      "Ueber 2-3 Wochen lernt {dogName}: hier loslassen lohnt sich.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "s-trigger-lesen",
    title: "Toilettendrang lesen lernen",
    shortDesc: "Bevor {dogName} loslaesst: schnueffeln, drehen, unruhig — du musst diese Zeichen kennen",
    intro: "Wenn du den Toilettendrang FRUEH erkennst, kannst du rechtzeitig rausgehen. Schnueffeln am Boden, im Kreis drehen, ploetzlich unruhig werden — das sind die Trigger.",
    steps: [
      "Beobachte {dogName} aktiv waehrend sie wach ist.",
      "Typische Trigger-Verhalten: am Boden schnueffeln, im Kreis drehen, ploetzlich aufstehen, zur Tuer schauen.",
      "Sobald du eines davon siehst: SOFORT rausgehen. Nicht warten.",
      "Auch in der Wohnung mitnehmen: schnell raus, NICHT erst Schuhe anziehen mit Verzoegerung.",
      "Im Garten oder draussen: an gewohnten Platz fuehren.",
      "Belohnung wie ueblich.",
      "Ueber Wochen wirst du immer schneller mit dem Erkennen.",
    ],
    phase: "fundament",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "s-unfaelle-managen",
    title: "Unfaelle managen: sauberer Umgang ohne Strafe",
    shortDesc: "Wenn ein Unfall passiert: ruhig saubermachen, NICHT schimpfen",
    intro: "Unfaelle gehoeren zum Lernprozess. Wer schimpft oder bestraft, macht alles schlimmer — {dogName} versteckt sich beim naechsten Mal nur. Sauberkeit + Enzym-Reiniger + Geduld.",
    steps: [
      "{dogName} hat in die Wohnung gemacht: KEIN Schimpfen, KEIN Nase-rein-druecken — das ist 1970er-Methoden, kontraproduktiv.",
      "Bringe {dogName} raus an den richtigen Platz — falls noch was kommt: dort belohnen.",
      "Reinige die Stelle GRUENDLICH mit Enzym-Reiniger (Tierhandlung).",
      "Normaler Reiniger reicht NICHT, der Geruch bleibt fuer den Hund da, sie pinkelt nochmal genau dort.",
      "Notiere den Unfall ins Tagebuch: wann, was, vorheriger Toiletten-Gang?",
      "Falls Unfaelle haeufig: Frequenz der Toilettenrunden erhoehen.",
      "Bei erwachsenen unreinen Hunden: Tierarzt-Check — Blasenentzuendung oder andere medizinische Ursachen ausschliessen.",
    ],
    phase: "steigerung",
    difficulty: "easy",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "s-stress-reduktion",
    title: "Stress-bedingtes Soiling reduzieren",
    shortDesc: "Wenn {dogName} aus Stress in die Wohnung macht: Stress-Faktor reduzieren",
    intro: "Manche Hunde machen unter Stress in die Wohnung — bei Gewitter, neuen Menschen, Veraenderungen. Loesung: Stress aktiv reduzieren, nicht das Soiling bestrafen.",
    steps: [
      "Identifiziere Stress-Trigger: Gewitter? Neue Menschen? Aenderungen im Tagesablauf? Trennungsangst?",
      "Reduziere Stress aktiv: Sicherheits-Decke, Beruhigungs-Marker, ggf. medizinische Unterstuetzung.",
      "Vor erwartetem Stress (z.B. Gewitter): extra Toilettenrunde davor.",
      "Waehrend Stress-Phase: ruhig bleiben, nicht aufgeregt werden.",
      "Falls Soiling waehrend Stress: ruhig reinigen, ohne Drama.",
      "Bei haeufigem Stress-Soiling: Tierarzt + Verhaltenstrainer einbeziehen, ggf. medizinische Unterstuetzung.",
    ],
    phase: "steigerung",
    difficulty: "medium",
    durationMin: 0,
    suitableFor: {},
  },
  {
    id: "s-naechtliche-blase",
    title: "Naechtliche Stubenreinheit aufbauen",
    shortDesc: "Welpen und unreine Hunde: vor dem Schlafen + ggf. mittendrin raus",
    intro: "Welpen und unreine Hunde brauchen oft eine naechtliche Toilettenrunde. Diese Woche baust du die nachtliche Routine auf, damit es trocken bleibt.",
    steps: [
      "Letzte Toilettenrunde direkt vor dem Schlafen.",
      "Bei jungen Welpen (8-16 Wochen): einmal nachts raus.",
      "Bei aelteren unreinen Hunden: erstmal alle 4-5 Stunden nachts raus, dann reduzieren.",
      "Naechtliche Runde: ruhig, kein Spiel — nur Toilette und zurueck.",
      "Belohnung wie tagsueber.",
      "Ueber Wochen baut sich die Blase auf: erst 4h, dann 6h, dann 8h durchhalten.",
      "Falls {dogName} nachts in die Wohnung macht: nicht schimpfen, lieber Toiletten-Routine engmaschiger.",
    ],
    phase: "generalisierung",
    difficulty: "medium",
    durationMin: 5,
    suitableFor: {},
  },
];

// ════════════════════════════════════════════════════════════════════
// Library-Registry
// ════════════════════════════════════════════════════════════════════

export const EXERCISE_LIBRARY: Record<ProblemKey, ExerciseTemplate[]> = {
  pulling: PULLING_EXERCISES,
  energy: ENERGY_EXERCISES,
  aggression: AGGRESSION_EXERCISES,
  mouthing: MOUTHING_EXERCISES,
  recall: RECALL_EXERCISES,
  barking: BARKING_EXERCISES,
  anxiety: ANXIETY_EXERCISES,
  jumping: JUMPING_EXERCISES,
  destructive: DESTRUCTIVE_EXERCISES,
  soiling: SOILING_EXERCISES,
};

// ════════════════════════════════════════════════════════════════════
// Helper: Problem-Label (deutsch) — fuer Plan-Titel + Intros
// ════════════════════════════════════════════════════════════════════

export const PROBLEM_LABELS_DE: Record<ProblemKey, string> = {
  pulling: "Leinenziehen",
  barking: "übermäßiges Bellen",
  aggression: "Aggression in Begegnungen",
  anxiety: "Trennungsangst",
  recall: "unzuverlässiger Rückruf",
  energy: "zu viel Energie",
  jumping: "Anspringen von Menschen",
  destructive: "Zerstörungsverhalten",
  soiling: "Stubenreinheit",
  mouthing: "Aufnehmen von Gegenständen",
};
